snyk/snyk-ls

infrastructure/cli/auth/provider.go
_This PR should fix scans not working in sublime due to an errant `break` in the `copyAuthURL` logic._
=> fix: copyAuthURL breaking Snyk in Sublime [ROAD-1166]

application/config/config.go, application/config/config_test.go, domain/snyk/scanner.go, infrastructure/cli/cli.go, infrastructure/cli/cli_fake.go, infrastructure/code/bundle.go, infrastructure/code/code.go, infrastructure/code/code_test.go, infrastructure/code/fake_snyk_code_api_service.go, infrastructure/iac/iac.go, infrastructure/oss/scanner.go, infrastructure/oss/scanner_test.go, internal/scans/running_scan.go, internal/scans/scan_progress.go
Product scanners avoid running several scans at once for the same paths. For OSS & IAC the previous scans are cancelled and restarted, and for Code the new scan will wait for the previous scan to finish
=> feat: One scan per folder [ROAD-1126]

infrastructure/cli/cli.go
_This PR should limit the concurrent CLI processes by using a semaphore. It also sets a 15 mins deadline on running CLI processes to guard against the CLI hanging._
=> feat: add cli concurrency limit [ROAD-1155]

application/config/config.go, infrastructure/cli/initializer.go, infrastructure/cli/initializer_test.go, infrastructure/cli/install/installer.go, infrastructure/segment/install_event.go, infrastructure/segment/install_event_test.go
If server is started first time and CLI is not found, IDE can issue `WorkspaceDidChangeConfiguration` notification. At this point CLI path won't be set, resulting in [UpdateSettings](https://github.com/snyk/snyk-ls/blob/692b48a2a0c941df409e3ca8a2cea524e84eede6/application/server/configuration.go#L69) reseting CLI path in `CurrentConfig` during download.
When download finishes Installer would report empty path to the initializer, resulting in `Could not find, nor install Snyk CLI` error.
To solve this, we'll assume CLI path is default, whenever client (IDE) reports us an empty string for cliPath in `WorkspaceDidChangeConfiguration`.
=> fix: CLI path reset during initial download [ROAD-1183]

.github/workflows/release.yaml
Pass in `id-token` permission to the github workflow
This commit also moves the login to earlier in the pipeline (so that we don't have to wait for the integration tests)
=> fix: Grant id-token permissions to the github workflow

infrastructure/cli/auth/provider.go, infrastructure/cli/cli.go, infrastructure/cli/cli_test.go, infrastructure/cli/environment.go, infrastructure/cli/environment_test.go
CLI crafts authentication url with wrong UTM parameters when LS is launched via VS Code (see `CLI_V1_PLUGIN`):
`https://app.snyk.io/login/cli?token=4bc3ddde-1209-4fef-b0e3-4a64fedc325c&utm_medium=cli&utm_source=cli&utm_campaign=CLI_V1_PLUGIN&utm_campaign_content=1.1032.0&os=darwin&docker=false`
vs. Eclipse:
`https://app.snyk.io/login/cli?token=4e29b656-90cb-42e5-90af-ce3512c19d59&utm_medium=cli&utm_source=cli&utm_campaign=ECLIPSE&utm_campaign_content=2.0.0.202209271622&os=darwin&docker=false`
=> fix: empty integration reported to CLI in auth provider [ROAD-1049]

domain/ide/workspace/workspace.go, infrastructure/cli/initializer.go
- Avoid "workspace scan" notification, as this is communicated via IDE progress elements.
- Clarify Snyk CLI notification
- Add successful and unsuccessful messaging to Snyk CLI downloads
Context:
https://snyk.slack.com/archives/G01QAALCGH4/p1666007565172169
**Old**
**New**
=> refactor: remove redundant notifications (ROAD-1049)

application/config/config.go, application/server/configuration.go, application/server/configuration_test.go, application/server/lsp/message_types.go, infrastructure/segment/client.go, infrastructure/segment/client_test.go, infrastructure/segment/install_event_test.go
Language Server clients may generate Device ID themselves for telemetry. We want to respect it in order to map it onto authenticated ID for analytical purposes.
=> feat: allow setting device Id by clients [ROAD-1049]

application/server/server_test.go, infrastructure/cli/initializer.go
Fixed an error where the `$/snyk.isAvailableCli` message is sent with an empty CLI path.
_(Note that the message is sent on line 117, so no further changes needed)_
=> [ROAD-1227] fix: CLI path not provided error

.goreleaser.yaml, Makefile, README.md, application/config/config.go, application/config/config_test.go, application/server/configuration.go, application/server/configuration_test.go, application/server/execute_command.go, application/server/execute_command_test.go, application/server/lsp/message_types.go, application/server/server.go, application/server/server_test.go, application/server/trust.go, application/server/trust_test.go, domain/ide/workspace/folder.go, domain/ide/workspace/folder_test.go, domain/ide/workspace/workspace.go, domain/ide/workspace/workspace_test.go, domain/ide/workspace/workspace_trust.go, domain/ide/workspace/workspace_trust_test.go, domain/snyk/command.go, internal/testutil/test_setup.go
Snyk Language Server by default has a workspace trust feature enabled. If a client asks for an untrusted folder to
be scanned, Snyk Language Server will prompt the user to trust the folder. The user can then choose to trust the folder
or decline it, which will result in either scanning the folder when choosing the former, or no activities from Snyk on that folder if choosing the latter. When a folder is trusted all sub-folders are also trusted. After a folder is trusted, Snyk Language Server notifies the Language Server Client with the custom `$/snyk.addTrustedFolders` notification, which contains the list of trusted folders.
A client can then implement logic to intercept this notification and persist the decision and trust in the IDE or Editor storage mechanism.
Trust dialogs can be …
=> feat: add trust management mechanism

README.md, application/config/config.go, application/config/config_test.go, application/server/configuration.go, application/server/configuration_test.go, application/server/lsp/severity_filter.go, application/server/server_test.go, domain/ide/workspace/folder.go, domain/ide/workspace/folder_test.go, domain/ide/workspace/workspace.go, internal/testutil/test_setup.go
- Enables client to filter issues by severity during runtime.
- Centralises filter instantiation to simplify future refactors, if needed.
=> feat: filter issues by severity during runtime [ROAD-1143]

infrastructure/cli/cli_fake.go, infrastructure/iac/iac_test.go, infrastructure/oss/oss.go, infrastructure/oss/oss_integration_test.go, infrastructure/oss/oss_test.go
Triggers new OSS scan after 24h without a scan to provide fresh OSS results to the user.
=> feat: schedule oss re-runs after 24h [ROAD-1220]

application/di/init.go, infrastructure/cli/auth/initializer.go, infrastructure/cli/auth/initializer_test.go, infrastructure/services/auth_service.go, infrastructure/services/auth_service_test.go, infrastructure/snyk_api/fake_api_client.go, infrastructure/snyk_api/snyk_api.go
_This PR should change how we check a user is authenticated by using an API endpoint instead of CLI auth. This should stop auth checks from writing to the config store.._
=> fix: Use API /user/me to check if user is authenticated [ROAD-1236]

application/server/server.go, application/server/server_test.go, domain/ide/converter/converter.go, domain/ide/hover/fake_service.go, domain/ide/hover/model.go, domain/ide/hover/service.go, domain/ide/hover/service_test.go
Previously, hovers were not correctly calculated, when 
- the hover was multi-line and 
- the last char position on the last line was < cursor position
The change switches usage from sourcegraph ranges to our Snyk domain ranges, as that type already has working helper functions to test for overlap. Also, it removes duplication of range/overlap logic.
=> fix: 🐛 correct hover / position overlap calculation [HEAD-53]

application/server/notification/scan_notifier.go, infrastructure/code/convert.go, infrastructure/code/convert_test.go
- Reports Snyk Code markers in the `snyk/scan` message to VS Code extension.
- Corrects issue line and column indices.
=> feat: report Code markers in "snyk/scan" message [HEAD-9]

infrastructure/code/backend_service_pact_test.go, infrastructure/code/bundle.go, infrastructure/code/code.go, infrastructure/code/code_test.go, infrastructure/iac/iac.go, infrastructure/oss/oss.go, internal/concurrency/atomic_map.go, internal/progress/progress.go, internal/testutil/test_setup.go, internal/uri/uri_util.go
When `limitToFiles` is omitted from request payload to `/analysis`, Snyk Code assumes that all workspace folders have been changed. This results in higher load on the engine.
This PR passes `limitToFiles` to the backend.
=> feat: pass limitToFiles to Code engine [HEAD-122]

infrastructure/code/code.go, infrastructure/code/code_test.go
Using relative paths in gitignore logic led to ignore `.`. Until we find the right fix, this uses absolute paths now.
=> fix: gitignore regression

.github/workflows/build.yaml, .github/workflows/release.yaml, .goreleaser.yaml, Makefile, application/server/server.go, application/server/server_test.go, domain/ide/workspace/folder.go
fix: report diagnostics from cache on "textDocument/didOpen"
Fixes switching between files in sublime, as sublime expects diagnostics to be reported anew when a file is opened.
Issue filed under: https://github.com/sublimelsp/LSP/issues/2200
=> fix: publish diagnostics from cache when file is opened

application/codeaction/codeaction.go, application/codeaction/codeaction_test.go, application/codeaction/handlers.go, application/di/init.go, application/server/server.go, application/watcher/file_watcher.go, application/watcher/file_watcher_test.go
Removes the code actions when the document is being edited as a temporary solution
=> fix: remove code actions when document has unsaved changes [HEAD-161]

application/config/config.go, application/config/config_test.go
Token provided wasn't used for default authentication method when querying Snyk API.
=> fix: ensure token is updated in app framework for default auth

go.mod, infrastructure/code/backend_service.go, infrastructure/code/backend_service_interface.go, infrastructure/code/backend_service_pact_test.go, infrastructure/code/backend_service_test.go, infrastructure/code/bundle.go, infrastructure/code/code.go, infrastructure/code/code_test.go, infrastructure/code/convert.go, infrastructure/code/convert_test.go, infrastructure/code/fake_snyk_code_api_service.go, infrastructure/code/path.go, infrastructure/oss/oss.go, infrastructure/oss/oss_test.go
- Use relative url encoded paths when communicating with Snyk Code API. 
- Update Go to 1.20
=> feat: use relative paths for communication with Code API [HEAD-223]

infrastructure/code/bundle.go
This follows upon #264 to use relative paths in calls to autofix
=> fix: use relative filepaths in calls to engine following #264

infrastructure/code/backend_service.go, infrastructure/code/backend_service_interface.go, infrastructure/code/backend_service_pact_test.go, infrastructure/code/bundle.go, infrastructure/code/bundle_uploader.go, infrastructure/code/code_test.go, infrastructure/code/fake_snyk_code_api_service.go, infrastructure/code/pacts/snykls-snykcodeapi.json, infrastructure/code/settings.go
Counterpart of the PR on the sast side which adds the filtering and prohibits the non-supported autofix extensions to have codeactions.
Side-effects:
- added `EncodePath(...)` as a followup to #267 
@bastiandoetsch, @michelkaporin, @asaf92 would you like to pick up from there and add pact testing etc? (not an expert)
=> feat(autofix): support extensions endpoint [ML-185]

infrastructure/iac/iac.go, infrastructure/iac/iac_test.go, infrastructure/iac/types.go
- Fixes the types for the IaC issue path. Currently the path is represented as a slice of string tokens, when in reality tokens can also be integers.
=> fix: IaC issue path

infrastructure/code/backend_service.go, infrastructure/code/convert_test.go
Redundant limitToFiles encode is happening currently, resulting in encoding encoded chars.
=> fix: remove redundant encode in Code scans

application/di/init.go, domain/snyk/scanner.go, domain/snyk/scanner_test.go, infrastructure/cli/cli.go, infrastructure/cli/environment.go, infrastructure/oauth/oauth_provider.go, infrastructure/oss/oss.go, infrastructure/services/auth_service.go
Sets additional environment variable to enable oauth when CLI is spawned. Also adds debug output and a "token-refresh" API call before scans are executed.
=> fix: enable oauth feature flag in cli calls when using oauth2

application/server/notification/scan_notifier.go, application/server/notification/scan_notifier_test.go, domain/ide/workspace/folder.go, domain/snyk/scan_notifier.go, domain/snyk/scan_notifier_mock.go, infrastructure/code/bundle.go, infrastructure/code/bundle_uploader.go, infrastructure/code/bundle_uploader_test.go, infrastructure/code/code.go
- Snyk Code didn't propagate error from GetFilters, resulting in UI showing success when API error happens
- UI was reporting success when IaC scan would finish, but Code is still running
=> fix: UI reporting success when product errors

infrastructure/code/code.go, infrastructure/filefilter/filter.go, infrastructure/filefilter/filter_test.go, internal/util/collections.go
Add caching to the file filtering in Snyk Code scans to prevent repeating CPU heavy calculations
=> refactor: added caching in code scans for ignore rules [HEAD-279]

infrastructure/filefilter/filter.go, infrastructure/filefilter/filter_benchmark_test.go, internal/util/math_extensions.go
Limits the number of CPU cores used for checking filtering rules
=> refactor: limit number of cores in file filtering

application/config/config.go, infrastructure/cli/environment.go, infrastructure/cli/environment_test.go, infrastructure/code/backend_service.go
When using CLI, the OAuth2 token should not be refreshed. Therefore, we use the SNYK_OAUTH_TOKEN variable, instead of INTERNAL_OAUTH_TOKEN_STORAGE.
=> feat: add SNYK_OAUTH_TOKEN when spawning CLI [HEAD-114]

application/config/config.go, application/di/init.go, application/di/test_init.go, infrastructure/code/code_test.go, infrastructure/oss/oss_test.go
This PR changes the default to add code actions to open issue related code actions to true, enabling it for VSCode, Eclipse & all LSP enabled Editors using Snyk Language Server. 
Notes: Test Initialization was moved from `init.go` to `test_init.go` therefore the big line change.
Only real changes are:
- config.go:L25 (changing default for learn code actions to true)
The rest is testing & mocking.
=> feat: enable code actions for snyk learn

application/config/config.go
The gaf configuration was incorrectly being populated from the CLI config file instead of using an in-memory object.
=> fix: use in memory config instead of file based

infrastructure/code/convert.go, infrastructure/code/convert_test.go, infrastructure/code/types.go
Temporarily ensure we can work with both old and latest autofix response payload. The old payload won't be sent any more after https://snyksec.atlassian.net/browse/ZEN-632 is in production on Code backend.
Upstream API response change PR: https://github.com/snyk/sast-analysis-api/pull/334
=> feat: respect new autofix payload [ZEN-632]

infrastructure/code/convert.go, infrastructure/code/convert_test.go, infrastructure/code/types.go
Fixes crash when mapping a type. It's redundant now, since we moved backend to the new payload.
```
panic: interface conversion: interface {} is map[string]interface {}, not code.autofixResponseSingleFix
goroutine 469 [running]:
github.com/snyk/snyk-ls/infrastructure/code.(*AutofixResponse).toAutofixSuggestions(0xc0022c96e0, {0xc003255357, 0x1e}, {0xc002ffc068, 0x6})
/Users/bdoetsch/workspace/snyk-ls/infrastructure/code/convert.go:490 +0x34e
github.com/snyk/snyk-ls/infrastructure/code.(*SnykCodeHTTPClient).RunAutofix(_, {_, _}, {{0xc00012ebc0, 0x40}, {0xc002c1e900, 0x40}, {0xc002ffc068, 0x6}, {{0xc002221fa0, ...}, ...}}, ...)
/Users/bdoetsch/workspace/snyk-ls/infrastructure/code/backend_service.go:436 +0x149b
github.com/snyk/snyk-ls/infrastructure/code.(*Bundle).autofixFunc.func1.1() …
```
=> fix: crash upon type mapping in Autofix

infrastructure/code/backend_service.go, infrastructure/code/backend_service_interface.go, infrastructure/code/bundle.go, infrastructure/code/convert.go, infrastructure/code/convert_test.go, infrastructure/code/fake_snyk_code_api_service.go
Fixes Eclipse plugin failing due to working with relative paths.
=> fix: autofix in eclipse

infrastructure/snyk_api/snyk_api.go
_This PR should remove the base64 encoding when sending the `x-snyk-ide` header_
=> fix: removed partial encoding from x-snyk-ide header

domain/snyk/issues.go
Follow-up on this https://github.com/snyk/snyk-ls/pull/325
The URL has now moved from https://snyk.io/security-rules to https://security.snyk.io/rules/cloud/  so I'm updating the URL example to reflect this.
The components that construct the URL have already been updated (snyk/CLI, snyk-iac-test)
=> chore: update documentation for snyk iac url

.gitignore, .snyk, domain/observability/performance/noop_span.go, go.mod, go.sum, infrastructure/sentry/init.go
Updated dependencies
- new go application framework supporting the new user agent
- update rest of dependencies to latest
Fixed Tracing/RequestID
- Sentry tracing should now work much better (we didn't explicitly enable it previously)
- RequestIDs should stay the same across calls, as Sentry is not dropping the transaction anymore
=> fix: sentry tracing and update deps

application/codeaction/codeaction.go, application/codeaction/codeaction_test.go, application/di/init.go, application/server/execute_command.go, application/server/execute_command_test.go, application/server/notification.go, application/server/notification_test.go, application/server/server_test.go, domain/ide/command/command_service.go, domain/ide/command/command_service_test.go, domain/snyk/command.go, domain/snyk/message.go, infrastructure/code/bundle.go, infrastructure/code/bundle_test.go, infrastructure/code/sast_enabled.go, infrastructure/code/sast_enabled_test.go
Addresses [this comment](https://github.com/snyk/snyk-ls/pull/311#discussion_r1213311622).
Uses value object instead of full dependency to work with ShowMessageRequest.
=> refactor: use commandData for ShowMessageRequest actions

application/di/init.go, application/di/test_init.go, domain/ide/codelens/codelens_test.go, domain/ide/command/logout_test.go, domain/ide/workspace/workspace_test.go, domain/observability/performance/instrumentor_test_types.go, domain/snyk/auth_service_impl_test.go, domain/snyk/scanner_test.go, infrastructure/code/backend_service_pact_test.go, infrastructure/code/backend_service_test.go, infrastructure/code/bundle_test.go, infrastructure/code/bundle_uploader_test.go, infrastructure/code/code_test.go, infrastructure/iac/iac_test.go, infrastructure/oss/oss_integration_test.go, infrastructure/oss/oss_test.go, infrastructure/oss/vulnerability_count_test.go
Substitutes the sentry instrumentor with a local one. Renamed the one used for testing, which only works locally, to localInstrumentor.
=> chore: disable sentry performance measurements

.circleci/config.yml, .gitleaksignore, .pre-commit-config.yaml
This PR adds secrets scanning to the repository. Developers should use the provided pre-commit hooks to prevent the secrets from being pushed to the repository. See https://pre-commit.com/ for details.
=> chore: configures secret scanning

getLanguageServer.sh
When possible, we should download binaries with transparent compression. The example script is adjusted, to use `--compressed` therefore.
=> chore: use curl with --compressed parameter in download script

infrastructure/iac/iac.go, infrastructure/iac/iac_test.go
Ensure that an IaC scan error causes the scan status to be set to Error instead of Success.
=> fix: incorrect iac scan status when an error occured.

getLanguageServer.sh
Previously, the arm64 on mac was not detected correctly. Also, downloads failed if no write access to /usr/local/bin was granted. This PR fixes the arm64 detection and writes to the current working directory, if writing to /usr/local/bin fails
=> fix: architecture determination for download script

application/config/config.go, application/config/config_test.go, infrastructure/amplitude/client_test.go
Checking for a "fedramp" part in the instance name is most likely not resilient enough, so we decided to only check the domain.
=> fix: only check snykgov.io domain to check if fedramp

ls_extension/main.go
_This PR should amend the interpretation of the `licenses` flag to correctly return licenses_
=> feat: call legacy cli command --about when receiving the licenses flag

CONTRIBUTING.md, Makefile, application/server/server.go, application/server/server_test.go, domain/ide/converter/converter.go, domain/ide/hover/fake_service.go, domain/ide/hover/model.go, domain/ide/hover/service.go, domain/ide/hover/service_test.go, domain/snyk/auth_service_impl_test.go
the colon in `C:\...` was url-encoded in the URI representation by VSCode, but the go URI library does not url encode this bit.
This led to the hover cache having a different key to associate hovers to files, so they weren't displayed.
=> fix: display hovers on windows [HEAD-420]

infrastructure/code/convert.go, infrastructure/code/convert_test.go
The marker for code results reaches one character too far, this fix changes this.
Before
After
=> fix: end position for code results

domain/ide/workspace/folder.go, domain/ide/workspace/folder_test.go, go.mod, go.sum, licenses/github.com/puzpuzpuz/xsync/v3/LICENSE
In certain constellations, the displayed number of issues varied over time even if the existing issues didn't change. There was a bug in a library used for caching issues, which triggered this bug. The PR updates the library in the affected use case.
Since this is a timing issue, it is difficult to provide a test to prove the fix.
=> fix: incorrect issue cache state [HEAD-972]

application/config/config.go, application/server/configuration.go, application/server/configuration_test.go
On the second time `writeSettings` is called, it doesn't get `enableAnalytics` flag. This change avoid this flag to be overridden after initialisation
=> fix: conditionally set analytics flag [HEAD-879]

infrastructure/oss/issue.go, infrastructure/oss/oss_test.go
Critical OSS issues were incorrectly mapped to high instead of critical.
=> fix: mapping of critical oss issues [HEAD-986]

domain/ide/workspace/folder.go, domain/ide/workspace/folder_test.go, domain/snyk/scan_result_processor.go, domain/snyk/scanner.go, infrastructure/cli/install/discovery_test.go, internal/product/product.go
- Replaced map-based severity counts with a new `SeverityCount` struct for clear and type-safe code
- Introduced a `ProductUnknown` constant to gracefully handle unidentified products
=> refactor: replace map-based severity count with structured types [HEAD-879]

Makefile, application/server/notification/scan_notifier.go, application/server/notification/scan_notifier_test.go, domain/snyk/issues.go, infrastructure/oss/issue.go, infrastructure/oss/issue_html.go, infrastructure/oss/issue_html_test.go, infrastructure/oss/template/details.html, infrastructure/oss/types.go, internal/lsp/message_types.go
Send a detailed view of an OSS Issue as an HTML from Language Server.
=> feat: create and send oss vulnerability issue panel as HTML [HEAD-149]

infrastructure/oss/issue.go, infrastructure/oss/issue_html.go, infrastructure/oss/issue_html_test.go, infrastructure/oss/types.go
_This PR fixes an issue in the IDE's details panel not showing the details path correctly._
=> fix: do not use pointer for matchingIssues in ossIssue struct

application/config/config.go, go.mod, go.sum, infrastructure/code/backend_service_pact_test.go, infrastructure/code/sast_local_engine_test.go
Enable adding auth headers for traffic to local code engine if configured.
=> fix: add auth header to local code engine requests as well [HEAD-1017]

Makefile, application/config/config.go, application/server/server.go, application/server/server_test.go, internal/logging/lsp_logger.go, internal/logging/scrubbingLogWriter.go, internal/logging/scrubbingLogWriter_test.go
We don't want to output the token in LS, so we now direct all log output through a filter/scrubber
=> feat: redact token in logging [HEAD-1019]

infrastructure/code/backend_service.go, infrastructure/code/backend_service_test.go
if a request fails, the changed code didn't check the response pointer, which caused a crash of the application.
=> fix: check pointer to avoid crash on failed HTTP requests

go.mod, go.sum
Fix disconnects of LSP client and server in case of proxy connection issues, caused by error messages written to stdout.
=> fix: possible lsp disconnects on proxy errors

infrastructure/oss/vulnerability_count.go
_This PR should change the vulnerability count text to omit severities where the count is 0._
Before
After
=> fix: vuln count text only shows count for severity X when severity X > 0

infrastructure/cli/cli_fake.go, infrastructure/oss/cli_package_scan.go, infrastructure/oss/cli_package_scan_test.go, infrastructure/oss/cli_scanner.go, infrastructure/oss/oss_test.go
fix: exclude `--all-projects` from package scan cli call
=> fix: exclude `--all-projects` from package scan cli call

application/server/notification/scan_notifier.go, application/server/notification/scan_notifier_test.go, domain/snyk/issues.go, infrastructure/code/convert.go, infrastructure/code/convert_test.go, internal/lsp/message_types.go
This PR adds the `PriorityScore` attribute to Snyk Code issues, enabling IDE integrations to display the severity score for code suggestions. 
The `PriorityScore` is propagated from the SARIF response and made available to the scan notification system.
This change can see propagated in Visual Studio Code in the PR https://github.com/snyk/vscode-extension/pull/422
|Before|After|
|-|-|
|<img width="1612" alt="missing-priority-score" src="https://github.com/snyk/vscode-extension/assets/1948377/e48f1cbe-dc62-4766-9793-587f18401e9e">|<img width="1612" alt="added-priority-score" src="https://github.com/snyk/vscode-extension/assets/1948377/79fcdbca-7803-4f7a-9c7a-91313d8d2245">|
HEAD-1187
=> feat: add Priority Score to Snyk Code Issues [HEAD-1187]

go.mod, go.sum, infrastructure/analytics/pact_test.go
Incorporate snyk/go-application-framework#122 which fixes the URL to the experimental analytics endpoint.
- ~~[ ] Linted~~
- ~~[ ] README.md updated, if user-facing~~
- ~~[ ] License file updated, if new 3rd-party dependency is introduced~~
=> upgrade GAF with analytics endpoint fix

.github/workflows/instance-tests.yaml, Makefile
This PR enables:
- `Test_SmokeWorkspaceScanOssAndCode`
- `Test_SmokeWorkspaceScanIacAndCode`
- `Test_SmokeWorkspaceScanWithTwoUploadBatches`
for the Standard environment
=> chore: enable smoke tests for Standard environment [IDE-56]

.github/workflows/instance-tests.yaml
IDE-57
Adding Slack notification to #dx_local_alerts if the smoke test cases fail.
=> feat: add Slack Notification When Smoke Test Fails

.github/workflows/instance-tests.yaml
This should add a link to the failing GH action run. Variables taken from [the docs](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context)
=> chore: add link to GH action in Slack notification

.github/workflows/instance-tests.yaml, Makefile
The `smoke-test-all` make target was misleading as it did not run all available smoke tests but rather a specific subset and only for the standard environment.
- Renamed `smoke-test-all` target to `instance-standard-test` in the Makefile.
- Updated the job name in GHA file to `instance tests (Standard)`.
- Updated the echo statement in the Makefile to _"==> Running instance tests for the Standard environment with proxy"_ for clarity.
Issue discussed [here](https://github.com/snyk/snyk-ls/pull/436#discussion_r1463045382)
=> refactor: rename `smoke-test-all` to `instance-standard-test` [IDE-56]

Makefile
For the Eclipse marketplace, we need to provide an update site for our plugin. The added automatic test verifies, that the site is reachable.
=> chore: add gcp bucket test to instance-standard-test makefile target

application/server/notification/scan_notifier.go, application/server/notification/scan_notifier_test.go, internal/lsp/message_types.go
Adds range information to scanIssues transferred via the custom $/snyk.scan message. This enables clients to display a range without having to analyse the diagnostics notifications.
=> feat: add issue range to scan issues

infrastructure/code/bundle.go, infrastructure/code/bundle_test.go
This PR fixes the behavior which only expected `<lang>/<ruleID>` returned from code, while code can also return `<lang>/<ruleID>/test`. The latter does not mean a lot but breaks our logic for determining the rule ID for autofix.
Works for VScode similarly to previous behaviour.
=> fix(code): fixes the behavior for test files [ML-568]

infrastructure/cli/install/releases.go
Correction for linting PR (#452) which inadvertently added an extra response body close.
Adding the defer immediately after checking the response error prevents a potential memory leak on non-200 response code.
=> chore: remove extra response body close

infrastructure/code/bundle.go, infrastructure/code/bundle_test.go, infrastructure/code/code.go, infrastructure/code/issue_enhancer.go, infrastructure/code/issue_enhancer_test.go
This part of the code will soon have some changes so that we can call off to the new Snyk Code scanning functionality in `code-client-go`. `code-client-go` will return SARIF and inside `snyk-ls` we are responsible for converting the SARIF to the `snyk.Issue` type used in the Language Server and enhance that issue with code actions etc. At the moment this functionality to enhance issues is done within the `Bundle` type, but it makes more sense to extract it into a new `IssueEnhancer` type (name is up for debate) and so then we can use this functionality both in the existing flow and then when we start using `code-client-go`. 
I've come to this conclusion by working on https://github.com/snyk/code-client-go/pull/2 and https://github.com/snyk/snyk-ls/pull/455 but these two PRs were getting …
=> refactor: extract issue enhancer funtionality [IDE-175]

domain/ide/command/get_feature_flag_status.go, domain/ide/command/get_feature_flag_status_test.go, domain/snyk/issues.go, infrastructure/code/code.go, infrastructure/code/code_test.go, infrastructure/snyk_api/fake_api_client.go, infrastructure/snyk_api/snyk_api.go, infrastructure/snyk_api/snyk_api_pact_test.go
In https://snyksec.atlassian.net/browse/IDE-172 we want to start using `code-client-go` behind the feature flag to branch off to the new flow and be able to manipulate ignored findings in our IDEs. `code-client-go` is currently not open sourced yet and we don't have a defined contract yet for what the data we return will look like, so for now this PR adds a separate flow for the Snyk Code scanning capabilities with ignores, which returns fake issues with fake ignore metadata. 
This PR will then unblock us working on the UI while the backend is sorted out.
Therefore, in this PR we are defining where the ignore information gets stored in the `snyk.Issue` type used by the Language Server.
I've run `make build-debug` and tested VSCode by changing the location of the LS binary.
I haven't …
=> feat: start branching off to new flow for snyk code ignores [IDE-172]

infrastructure/learn/service.go, infrastructure/learn/service_test.go
Previously, a lesson was only associated with one ecosystem. Now it is associated with all ecosystems.
=> fix: associate learn lessons with all ecosystems [IDE-203]

infrastructure/learn/pacts/snykls-snyklearn.json
The `snyk-ls` binary hasn't released in a while because the integration tests have failed. The integration tests fail because of a broken `pact` contract. They don't run in the CI/CD in PRs, only in `main`, so we didn't realise code changes broke them.
The code changes are in https://github.com/snyk/snyk-ls/pull/466.
=> test: fix pact learn tests

.github/workflows/instance-tests.yaml
- Previously, a Slack notification was sent whenever a build failed or was cancelled, regardless of the event type. This included push events to working branches
- This change will reduce the number of Slack notifications, particularly for ongoing work in development branches.
- Failures in more critical scenarios, like pull requests or main branch updates, will continue to trigger Slack notifications
=> chore: exclude notifications for `push` events

application/server/notification/scan_notifier.go, application/server/notification/scan_notifier_test.go, domain/snyk/issues.go, infrastructure/code/code_html.go, infrastructure/code/code_html_test.go, infrastructure/code/convert.go, infrastructure/code/convert_test.go, infrastructure/code/template/details.html, infrastructure/code/types.go, internal/lsp/message_types.go
This is the first PR of many related to the migration of the Code Issue panel to Language Server. This PR adds the initial HTML template for the Code Issue panel serving parts of the **Heading** and **Data Flow.**
How to test it:
- Use IntelliJ to trigger a Code Scan (FF required)
- Inspect the Language Server logs and look for the generated HTML (`additionalDataDetails := getDetailsHtml(d)`) with all the placeholders populated.
👀 Important note: **styling** and **actions** will be addressed in future PRs.
|IntelliJ UI and generated HTML|
|-|
|![IntelliJ2LS](https://github.com/snyk/snyk-ls/assets/1948377/fb6a3b74-babb-416a-88ee-71976437d4ba)|
=> feat: add code template [IDE-180]

infrastructure/code/code_html.go, infrastructure/code/code_html_test.go
If we want to be able to navigate to the right line in the file we need to provide some extra values for the IntelliJ plugin. This PR adds them as attributes on the `span` which contains the file path. Then in IntelliJ we can add a listener for that `span` and use the attributes to navigate tot he line.
This can be tested with IntelliJ by running https://github.com/snyk/snyk-intellij-plugin/pull/497.
=> fix: data flow html to aid with interactions [IDE-216]

application/config/config.go, infrastructure/cli/initializer.go, infrastructure/cli/install/downloader.go, infrastructure/cli/install/installer.go
This changes the download of the CLI in a minor way:
- it does not search for a CLI in the system path anymore and chooses an arbitrary file that is called snyk
- it downloads the CLI in a directory below the actual destination directory, so chances are high, it can finish once it's begun
- it creates the necessary directory tree before trying to move
=> fix: improve resiliency of CLI download [IDE-90]

go.mod, go.sum
The LS can now upgrade to the latest `code-client-go` version, so that we return the real findings for repos from the Analysis API.
=> feat: LS renders real findings for consistent ignores

infrastructure/snyk_api/snyk_api.go, infrastructure/snyk_api/snyk_api_pact_test.go
We are changing the `customEndpoint` to be `api.snyk.io`. It seems that when it's `app.snyk.io/api` this API does not require the `v1` but when it's `api.snyk.io` it does, otherwise it returns a 404. We don't want to break backwards compatibility so this change optionally adds `/v1` so that we can change the default `customEndpoint` correctly.
We tried to do this in IntelliJ but it causes a bug instead where this `/v1` is added to all APIs and not all of them requite it: https://github.com/snyk/snyk-intellij-plugin/blob/227befec201d4b47ad05a263c9625bb97c07bb33/src/main/kotlin/snyk/common/CustomEndpoints.kt#L76. We are fixing this in https://github.com/snyk/snyk-intellij-plugin/pull/523 and instead doing it in the LS, so that it applies to all IDEs.
🚨After having merged, please update the …
=> fix: append v1 to sast settings URL [IDE-126]

.github/workflows/instance-tests.yaml
- Slack notification gets triggered by `instance-tests[MT1, MT3]` and `instance-standard-test`. Before it was only attached to `instance-standard-test`
- Display more detailed information in Slack alert
- Fixed conditional to only alert when the failure happens in the `main` branch
IDE-298
=> refactor: display detailed informantion in Slack alert [IDE-298]

application/server/notification/scan_notifier.go, application/server/notification/scan_notifier_test.go, domain/snyk/issues.go, infrastructure/oss/issue.go, infrastructure/oss/issue_html.go, infrastructure/oss/issue_html_test.go, infrastructure/oss/oss_test.go, infrastructure/oss/types.go, internal/lsp/message_types.go
Refactors the types used for OSS so that:
- they're used consistently and so the OSS scan deals with `oss.ossIssue`, the rendered HTML deals with `snyk.OssIssueData`, and the `snyk.scan` notification deals with `lsp.OssIssueData`, which is converted from `snyk.OssIssueData` (before this change the rendered HTML dealt with `oss.ossIssue` directly, and so the data given to `snyk.scan` and to the HTML logic differed)
- as a result, we are able to easily include new fields in the `snyk.scan` notification that can be used to build the UI (e.g. `MatchingIssues`, `Lesson`, `Identifiers`)
This will be the building block for rendering OSS vulnerabilities in IntelliJ via the LS, but not from HTML yet.
Tested in …
=> refactor: oss issue data [IDE-283]

application/server/notification/scan_notifier.go, application/server/notification/scan_notifier_test.go, internal/lsp/message_types.go
Adds a `ruleId` field to the LS message so that in IntelliJ we can include it in the rendered UI.
=> feat: include ruleId in LS response for OSS [IDE-238] 

.github/workflows/build.yaml, .github/workflows/release.yaml, domain/ide/command/get_feature_flag_status.go, infrastructure/code/code.go, infrastructure/snyk_api/snyk_api.go
- Change log level from error to debug for 403 Forbidden responses in `FeatureFlagStatus`
- Provide clearer debug messages when the feature flag is disabled
New Messages:
```bash
// Startup:
// ======
DBG snyk_api.FeatureFlagStatus - Getting feature flag status path=/v1/cli-config/feature-flags/snykCodeConsistentIgnores?org=org_id
DBG snyk_api.FeatureFlagStatus - Feature flag 'snykCodeConsistentIgnores' is disabled
// When settings change
// =================
DBG snyk_api.FeatureFlagStatus - Getting feature flag status path=/v1/cli-config/feature-flags/snykCodeConsistentIgnores?org=org_id
DBG snyk_api.FeatureFlagStatus - Feature flag 'snykCodeConsistentIgnores' is disabled
DBG featureFlagStatus.Execute - …
```
=> fix: handle 403 responses gracefully for feature flags checks [IDE-328]

infrastructure/oss/cli_scanner.go, infrastructure/oss/oss_test.go
Add `--all-projects` flag to scans by default
=> feat: add `--all-projects` flag to open source scans by default [IDE-318]

infrastructure/code/autofix.go, infrastructure/code/issue_enhancer.go
=> fix: encode paths correctly for autofix in windows

infrastructure/code/code_html.go, infrastructure/code/code_html_test.go, infrastructure/code/template/details.html
Removes the custom IntelliJ styling for the HTML so that it can be injected from the IDE.
=> feat: remove custom styling and inject it from IDE [IDE-240]

infrastructure/code/template/details.html
Refactors the logic for switching tabs in HTML for both the main tabs and the example commit fixes tabs.
The selectors we were using were not specific enough so when switching between the main tabs, we would remove the `is-selected` class from the example commit fixes tabs too. By adding a more specific class to each tab and selecting based on that, we don't need to have complicated logic for remembering what the last selected tab was. This greatly simplifies the code in the JS.
https://github.com/snyk/snyk-ls/assets/81559517/14bcc012-0a84-410a-970f-8f5aee03ae1a
=> refactor: js logic for swapping tabs

infrastructure/code/code_html.go, infrastructure/code/code_html_test.go, infrastructure/code/template/details.html
This PR adds a link to the GitHub repo for **FIXED CODE EXAMPLES** tabs
https://github.com/snyk/snyk-ls/assets/1948377/fa1d5271-f6ea-4e54-9467-de68a1493121
=> chore: add repo link to repo tab name [IDE-381]

.github/workflows/build.yaml
- Use the new argument for skip from goreleaser
=> fix: go releaser argument for skip publish

infrastructure/code/issue_enhancer.go, infrastructure/code/issue_enhancer_test.go
Removes the AI fix code action and code lens if the issue is ignored.
To test it manually, apply this hack in `snyk-ls` until AI fixes work:
```
diff --git a/infrastructure/code/convert.go b/infrastructure/code/convert.go
index 94db11a..40459dc 100644
--- a/infrastructure/code/convert.go
+++ b/infrastructure/code/convert.go
@@ -366,7 +366,7 @@ func (s *SarifConverter) toIssues(baseDir string) (issues []snyk.Issue, err erro
Cols:               [2]int{startCol, endCol},
Rows:               [2]int{startLine, endLine},
IsSecurityType:     isSecurityType,
-                               IsAutofixable:      result.Properties.IsAutofixable,
+                               IsAutofixable:      true, …
```
=> fix: hide ai fix code action if ignored [IDE-223]

infrastructure/code/code_html.go, infrastructure/code/code_html_test.go
This PR maps the `reasonType` defined by the [Policy](https://github.com/snyk/policy/blob/39a6316bfa435a7dbd68295d065c6789b7bd331c/lib/add.ts#L7C1-L10) lib to the copy shown in the Web UI
|Web UI|Before|After|
|-|-|-|
|![image](https://github.com/snyk/snyk-ls/assets/1948377/37326ae4-6351-42f0-8654-7751b4b8abd2)|<img width="768" alt="image" src="https://github.com/snyk/snyk-ls/assets/1948377/8d9c0ae3-3f19-4a7a-b44d-52d4aa5b7c6d">|<img width="767" alt="image" src="https://github.com/snyk/snyk-ls/assets/1948377/6b3b7073-3249-44d8-ac45-e88c355ce2de">|
=> chore: parse ignore category value to copy

infrastructure/code/code_html.go, infrastructure/code/code_html_test.go, infrastructure/code/template/details.html
Moves over the common HTML and styling from VSCode so that eventually it can be used to render this panel in IntelliJ. In https://github.com/snyk/vscode-extension/pull/467 we can see the changes needed to add extra styling and javascript for VSCode and in https://github.com/snyk/snyk-intellij-plugin/pull/541 we completely hide this panel for IntelliJ.
See screenshots in linked PRs.
=> feat: ai fix html [IDE-375]

infrastructure/code/code.go, infrastructure/code/code_test.go
The vulns get returned with AI fixes but the diffs that get generated from the UI when trying to generate an AI fix wouldn't work. This it because of this line of code: https://github.com/snyk/snyk-ls/blob/6de43f05fd81255636d2a70605719fb7b0907c5a/infrastructure/code/autofix.go#L72
Added a fix which can be found in the old flow too, where we set the bundle hash on the scanner. Added a test so that next time we change this code we don't forget to set the bundle hash.
To test manually, best to build this version of VSCode: https://github.com/snyk/vscode-extension/pull/467.
=> fix: store bundle hash for ai fix [IDE-380]

infrastructure/code/code_html.go, infrastructure/code/code_html_test.go, infrastructure/code/template/details.html
This PR refactors the layout of fixed code examples by replacing the tab-based navigation with arrow-based navigation. It also includes several styling and script improvements.
- Removed the Community Examples tab layout.
- Implemented arrow-based navigation for fixed code examples.
- Reorganised constants, variables, and functions.
- Moved DOM-dependent functions inside `DOMContentLoaded`.
|IntelliJ|VSCode|
|-|-|
|<img width="1530" alt="image" src="https://github.com/snyk/snyk-ls/assets/1948377/206e0c75-a109-469c-a321-1e7bbe81f10d">|<img width="1531" alt="image" src="https://github.com/snyk/snyk-ls/assets/1948377/4eced6f2-5bfa-4a57-a9f4-27ffef2157a4">|
=> refactor: replace tabs with arrows [IDE-294]

infrastructure/oss/range_finder.go, infrastructure/oss/range_finder_test.go
Any range finding using package manager that are not NPM or Maven, caused a panic in open source scan.
=> fix: panic when using default finder findRange

go.mod, go.sum
Includes the following changes:
- https://github.com/snyk/code-client-go/releases/tag/v1.7.2
- https://github.com/snyk/code-client-go/releases/tag/v1.7.3
- https://github.com/snyk/code-client-go/releases/tag/v1.8.0 - where `SnykCodeAnalysisTimeout` becomes necessary, but it's already defined in `snyk-ls`
=> feat: update code-client-go to v1.8.0 [IDE-399]

CONTRIBUTING.md, docs/ui-rendering.md
This PR adds a guide on how to render UI components using the Language Server for the Snyk Code Issues across different IDEs, specifically focusing on VSCode and IntelliJ.
This screenshot is for the example added in the `ui-rendering.md` so I can add this link in the MD.
=> docs: UI rendering with Language Server

infrastructure/analytics/analytics.go
LS should not return an error to the IDEs if the analytics service isn't available or the call returns an error. Instead, it should just log.
=> fix: only log msg when not succeeding to send event to endpoint [IDE-418]

.github/create-cli-pr.sh
- uses same branch and title all the time
=> feat: update existing PR

infrastructure/code/convert.go, infrastructure/code/convert_test.go, infrastructure/code/issue_enhancer.go, infrastructure/code/issue_enhancer_test.go
We want to continue hiding the code actions and code lenses for ignored findings that have AI fixes. But we want the Fix Analysis tab to show AI fixes, so that issues that are temporarily ignored because of noise can be fixed if the developer chooses to. So the `HasAIFix` boolean needs to be configured.
Also sets the reason for an ignore to a default `None given` which matches what the UI shows.
=> fix: configure AI fix boolean even if issue is ignored [IDE-435]

application/server/server.go, application/server/server_test.go, internal/uri/uri_util.go, internal/uri/uri_util_test.go
This PR triggers a workspace scan when the `.snyk` file was saved.
https://github.com/snyk/snyk-ls/assets/1948377/d9f761f9-d692-4c48-b77e-15bc5181896a
=> fix: trigger folder scan when `.snyk` file changes [IDE-253]

infrastructure/code/code_html.go, infrastructure/oss/issue_html.go, infrastructure/oss/issue_html_test.go, infrastructure/oss/template/details.html, internal/html/html.go
This PR refactors the HTML template used for the OSS Sugestion Panel so that it's more secure and uses the `html/template` library. This also refactors the template so that it injects icons directly in LS and so other IDEs don't need to know what icons to inject. It adds a `${ideStyle}` variable so that in both VSCode and IntelliJ we can inject the IDE specific styling, like we do for Snyk Code.
To test this, need to use https://github.com/snyk/vscode-extension/pull/482.
=> feat: refactor the HTML to use html/template and to inject styling for other IDEs [IDE-326]

infrastructure/oss/issue_html.go, infrastructure/oss/issue_html_test.go, infrastructure/oss/template/details.html
Fixes some small UI problems in the OSS suggestion panel:
- the `Introduced Through` overview section should have the packages separated by comma and not as separate components on individual lines
- the `Detailed Paths` section in IntelliJ needs to render only the top 3 elements. It doesn't seem like VSCode deals with that today but it would be a good thing to have.
Have tested it with `target-service`.
Before:
After:
=> fix: introduce throughs and detailed paths in html of oss

domain/ide/command/command_factory.go, domain/ide/command/get_active_user.go, domain/ide/command/get_active_user_test.go, domain/ide/command/get_feature_flag_status.go, domain/ide/command/get_feature_flag_status_test.go, domain/ide/command/report_analytics.go, domain/ide/command/report_analytics_test.go, domain/ide/command/sast_enabled.go, domain/ide/command/sast_enabled_test.go, infrastructure/authentication/auth_service_impl.go
Checks for authentication before executing commands that need it:
- reportAnalytics command
- getActiveUser command
- sastEnabled command
- getFeatureFlag command
Also, cache calls to the API for authentication. This should at least half the calls to registry / authentication services.
=> fix: check if authenticated before executing commands

infrastructure/oss/issue_html.go, infrastructure/oss/issue_html_test.go, infrastructure/oss/template/details.html
This PR surfaces the Policy notes when a user applies Severity change rules or add Annotations to a policy
- Added support for displaying policy data in OSS issue details.
- Updated the `details.html` template to conditionally render policy information if present.
- Updated unit tests to cover policy data rendering
|Policy With Annotations|With Severity Change|
|-|-|
|<img width="2056" alt="image" src="https://github.com/snyk/snyk-ls/assets/1948377/f03e85e8-1184-4b2e-b671-37cbe7a25096">|<img width="2056" alt="image" src="https://github.com/snyk/snyk-ls/assets/1948377/f636a43f-e077-4eb3-884e-5c7bbb85068f">|
=> feat: render Policy details for Open Source [IDE-454]

README.md, application/config/config.go, application/server/configuration_test.go, infrastructure/authentication/cli_provider_test.go, infrastructure/cli/environment_test.go, infrastructure/learn/service_test.go
snyk.io/api is the legacy and deprecated API url.
Let's favour api.snyk.io instead.
=> refactor: set default api url to api.nyk.io

README.md, application/config/client_settings.go, application/server/configuration.go, application/server/configuration_test.go, application/server/notification.go, application/server/server_smoke_test.go, domain/ide/workspace/workspace.go, infrastructure/code/code.go, infrastructure/code/convert.go, internal/git_config/git_config.go, internal/types/lsp.go
This PR enables IDE/LS to communicate SCM data between IDE and LS.
IDEs can send a folderConfig JSON struct as part of the InitializationOptions / Settings that contains the chosen base branch. This selection is saved in gitconfig in our own subsection.
On adding a workspaceFolder to LS, LS queries the underlying git repository for all local branches and the currently configured base branch. in a subsection of the gitconfig. If none is configured it falls back to first use `gitconfig.init.DefaultBranch`, and if that's empty, main.
Gitconfig structure:
```
snyk
|-- folderPath 
| baseBranch = main
```
Example of folderConfig:
```
{"baseBranch":"main","folderPath":"/var/folders/c_/lj9ppcwx2jnf8jhdhcqgz3940000gn/T/Test_SmokeWorkspaceScanOSS_and_Code2792167781/001/1","localBranches":["main"]} …
```
=> feat: share scm information between IDE and language server [IDE-451]

README.md, application/codeaction/codeaction.go, application/config/config.go, application/server/configuration.go, application/server/configuration_test.go, domain/ide/codelens/codelens.go, infrastructure/oss/code_actions.go, infrastructure/oss/issue.go, infrastructure/oss/oss_test.go, internal/types/lsp.go
Before, open description in browser was added as a code action by default
Now, the open action is gone, and the fix description has been updated
A configuration setting has been added, to be able to enable it via settings/initializationOptions.
=> fix: remove open browser action by default, make it configurable

infrastructure/oss/cli_package_scan_test.go, infrastructure/oss/cli_scanner.go, infrastructure/oss/issue.go, infrastructure/oss/types.go, infrastructure/oss/types_test.go
Gradle multi module projects are reported differently in the JSON output. This PR adjusts parsing and issue key generation.
=> fix: parse gradle multiprojects correctly [IDA-39]

application/server/server_smoke_test.go, application/server/server_test.go, application/server/trust_test.go, domain/ide/workspace/folder.go, internal/testutil/test_setup.go
Previously, the sub directory check for trust was just checking if the trusted directory had the same prefix. Now it's checking the relative path.
Example:
Trusted: /a
Untrusted: /a-123
Previously, /a-123 would be trusted. This PR fixes that.
=> fix: check if path is a sub directory correctly

application/server/constants.go, application/server/parallelization_test.go, application/server/server_smoke_test.go, application/server/server_test.go, application/server/trust_test.go, infrastructure/cli/cli.go, infrastructure/oss/cli_scanner.go
This sets the max parallel execution of CLI to the number of cores - 2 or 1, whichever is higher. It also fixes a concurrency issue when retrieving open source issues and storing them in the scanner-local caches by using the scanner mutex.
A smoke test was added to check parallelization.
=> chore: tweak parallelization of CLI, add test

application/server/execute_command_test.go, application/server/parallelization_test.go, domain/ide/command/login.go, infrastructure/authentication/auth_configuration.go, infrastructure/authentication/auth_service_impl.go
Facilitate client handling by returning the authentication token after successful login. Also parallelize cloning in parallel test to speed it up (now it's 3x faster on my local machine).
=> feat: return token in login command [IDE-458]

application/config/config.go, application/server/notification.go, go.mod, go.sum
This pulls in a better scrubLogger that does concurrency locks when needed. Also adds accessToken and refreshToken to dict on token change.
Example:
```
[Info  - 8:51:41 AM] 2024-07-31T08:51:41+02:00 INF initializeHandler - RECEIVING params={...,"token":"{\"access_token\":\"***\",\"token_type\":\"bearer\",\"refresh_token\":\"***\",\"expiry\":\"2024-07-31T08:47:33.42171+02:00\"}",...}
```
=> chore: improve scrubbing in logs

infrastructure/oss/cli_package_scan_test.go, infrastructure/oss/cli_scanner.go, infrastructure/oss/cli_scanner_test.go, infrastructure/oss/types_test.go
Gemfile package manager locations were reported differently. The parsing now has a "panic" mode to try out different combinations if the standard doesn't work and uses stat to verify.
=> fix: add parsing edge case for submodule gemfiles [IDE-517]

domain/ide/workspace/ui/diagnostics_overview.go, domain/ide/workspace/ui/template/diagnosticsOverview.css, domain/ide/workspace/ui/template/diagnosticsOverview.html, infrastructure/iac/iac_html.go, infrastructure/iac/template/index.html
This PR fixes the value generated for the nonce value. Previously, the `nonce` was treated as a plain string, which led to improper escaping. By using `template.HTML`, we ensure that the `nonce` is inserted as **raw HTML**.
This change also adds at the The Content-Security-Policy header the missing `'nonce-ideNonce'` attribute, which is necessary for allowing IDEs to inject their specific styles. .
=> fix: escape nonce value with `template.HTML` [IDE-488]

infrastructure/code/autofix.go, infrastructure/code/snyk_code_http_client.go
We noticed, that while for Analysis, the `requestId` is visible at the `info` level, we don't have the same for autofix -- which would be useful when the users want to report the issues (without going through the complex procedure of switching the debug level on).
=> chore(autofix): more visible logging

Makefile, application/codeaction/codeaction.go, application/codeaction/codeaction_test.go, application/server/codeaction_handlers.go, application/server/server_test.go, infrastructure/code/issue_enhancer.go
Eclipse and VSCode have slightly different behaviours. To cater for Eclipse's behaviour (HEAD-229) we added execution of commands during resolution of code actions. This is not correct and only worked, because we returned an empty code action afterwards to Eclipse which overwrote the command earlier contained.
In VSCode, the command of the code action is not overwritten by the resolved code action, thus `executeCommand` was called both in resolution and normal command execution.
This implementation difference abides by protocol, but our returning changed fields after executing the command does not. The PR fixes this incorrect behaviour.
=> fix: do not execute code action commands twice [IDE-506][HEAD-229] 

application/config/config.go, application/server/server.go, infrastructure/authentication/auth_configuration_test.go
IDEs should not share credentials. Now the shared storage file is only shared by IDE name.
=> fix: use IDE-specific storage

application/server/server_test.go, infrastructure/oss/cli_scanner.go, infrastructure/oss/oss_test.go
if --file is given, --all-projects cannot be used, as they are mutually exclusive. This commit introduces a blacklist that blocks automatic addition of `--all-projects`.
=> fix: do not add `--all-projects` if `--file` is given [IDE-567]

infrastructure/oss/cli_scanner.go, infrastructure/oss/cli_scanner_test.go
Previously, a file tree as the following was causing problems in NPM SCA scans:
```
project
|-package.json
|-frontend
|--package.json
```
The JSON result parser would not identify the right package.json (unfortunately, the CLI does not report the absolute path of the package manager file).
=> fix: also display files for sub modules in npm [IDE-573]

application/config/config.go, application/config/config_test.go
Load environment from shell environment. This reduces the number of errors caused by configuration mismatches.
=> feat: read shell environment on startup

.github/workflows/build.yaml, .github/workflows/create-cli-pr.yaml, .github/workflows/instance-tests.yaml, .github/workflows/release.yaml, Makefile, application/di/test_init.go, application/server/server.go, infrastructure/authentication/auth_configuration.go, infrastructure/authentication/auth_service_impl.go, infrastructure/code/snyk_code_http_client_test.go, infrastructure/learn/mock_learn/service_mock.go, infrastructure/learn/service.go, infrastructure/learn/service_test.go, internal/vcs/checkout_handler.go, internal/vcs/checkout_handler_test.go
Moves the learn service initialization to after language server is initialized. Logs truncated refresh tokens for error debugging.
=> fix: move learn service cache init to after ls startup & init

domain/ide/command/code_fix_diffs_test.go
Enables the fix code diffs test for Windows. It seems adapting the bundle hash is enough.
In Windows, a directory path can sometimes start with a backslash (\), and this usually happens in specific contexts or for certain reasons:
1. Relative Path to the Root of the Current Drive
When a directory path starts with a backslash (e.g., \folderPath), it refers to an absolute path relative to the root of the current drive. In this case, Windows assumes the drive you're currently on and applies the path starting from the root of that drive.
Example:
If you're on drive C:, the path \folderPath refers to C:\folderPath.
When is this used?
It's common in scripts or command-line usage where the drive context is known and fixed (like C:). This allows the user to quickly reference a folder from the …
=> fix: autofix: enable code fix diff test on windows

application/server/configuration.go, domain/ide/workspace/folder.go, infrastructure/code/convert.go, internal/delta/delta_finder_test.go, internal/delta/fuzzy_matcher_test.go
* Severity filter when delta is enabled.
* Ensure Fingerprint.Identity is set.
* Added tests to ensure that Fingerprint.Identity won't be overwritten by delta finder if it exists.
=> fix: severity filters when delta is enabled

infrastructure/code/template/details.html, infrastructure/iac/iac_html_test.go, infrastructure/iac/template/index.html, infrastructure/oss/template/details.html
If a target is set on a link, JCEF components cannot open the link in an external browser
=> fix: remove target="_blank" from html sources [IDE-677]

infrastructure/code/convert.go, infrastructure/code/convert_test.go
The file reading process for DeepCode AI Fix was wrong because it was not using the `DecodePath` function as it is done for other places in the codebase. This leads to AI Fix not working on files with spaces or other characters which are HTML encoded. 
There were also no tests for the conversion function `toUnifiedDiffSuggestions`. 
This PR:
- adds a test for `toUnifiedDiffSuggestions`.
- fixed the bug around HTML encoding in filepath by using `DecodePath`
- adds another test suit to test `toUnifiedDiffSuggestions` under HTML Encoding
Before the fix
[ai_fix_space_bug.webm](https://github.com/user-attachments/assets/e104c8a0-5be6-494d-b443-38366de4786d)
After the fix
[ai_fix_spaces_fixed.webm](https://github.com/user-attachments/assets/6f64335a-7d2c-4195-a51f-3725ea0a0ec8) …
=> fix/autofix: fix html encoding and add test for toUnifiedDiffSuggestions

application/config/config.go, internal/vcs/git_cloner.go, internal/vcs/git_cloner_test.go
=> fix: set remote URL after cloning git repo [IDE-674]

infrastructure/code/convert.go, infrastructure/code/convert_test.go
Autofix Code action flow does not work on file names with HTML encoded characters. We show the user that everything went correctly and show the popup with the Congratualitons message but we fail to modify the file. The file content stays the same.
This PR fixes this issue.
Before
[code_action_bug.webm](https://github.com/user-attachments/assets/e1256c97-42e2-4460-a177-451601cf9ba2)
After
[code_action_fix.webm](https://github.com/user-attachments/assets/59162aad-d559-447a-b378-ceef58ad59da)
=> fix: autofix html decoding

README.md
Update README with more examples of custom notifications and types which may be useful to integrating with the Snyk Language Server.
Rename "payload" to "params", "response" to "example" in notification docs. This is to better align with the wording used in the [LSP specification regarding notifications](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#notificationMessage).
=> chore: improve custom lsp extension docs

README.md, application/server/server_test.go
Removing a phantom attribute that doesn't actually exist in the Diagnostic type, from README examples.
=> chore: correction on diagnostic example in readme

application/server/server.go, application/server/server_test.go, infrastructure/cli/install/downloader_test.go, infrastructure/cli/install/releases.go, infrastructure/cli/install/releases_test.go
- enable concurrent processing
- change CLI download URL
=> fix: concurrent processing in server, switch CLI download URL

application/server/server_smoke_test.go, infrastructure/cli/install/downloader.go, infrastructure/iac/iac_html.go, infrastructure/iac/iac_html_test.go, infrastructure/iac/template/index.html, infrastructure/iac/template/styles.css, internal/progress/progress.go
This is the logic needed for adding the IaC ignore button.
It has the HTML which has the button, hidden by default, enabled in **IntelliJ**.
A `FilePath` was also added to the TemplateData which is needed to trigger the IgnoreService for the specific issue, and the before named 'Path' variable was renamed to `ResourcePath` which is a more accurate name for what it represents.
A file path was also added to the template for enabling to execute the ignore issue comand which also needs file path.
=> fix: add ls part for iac ignore button [IDE-683]

infrastructure/code/template/details.html, infrastructure/iac/iac_html.go, infrastructure/iac/iac_html_test.go, infrastructure/iac/template/index.html, infrastructure/iac/template/scripts.js
Moved the IaC ignore in file JS logic from the IntelliJ plugin to the `scripts.js` file in the IaC template
Added Scripts attribute in the template data from which we inject into the HTML and added it to the template.
=> chore: move iac ignore scripts from intellij plugin to ls

infrastructure/code/code_html.go, infrastructure/code/code_html_test.go, infrastructure/code/template/details.html
This PR fixes DataFlowItems not being displayed in order, previously we used a map, which doesn't guarantee order, according to Go docs **_"The iteration order over maps is not specified and is not guaranteed to be the same from one iteration to the next"_** 
To solve this while also being able to have a map and access the DataFlowItems by the `fileName` as key, a slice is created that uniquely holds the fileNames (keys) of the map.
In the HTML template we iterate over the keys slice ( which is indexed in order ), and access the map by the key from current iteration.
=> fix: data flow order for code [IDE-763]

go.mod, go.sum
Upgrade to mitigate:
https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMGOMARKDOWNMARKDOWNPARSER-8220052
=> fix: upgrade vulnerable pkg gomarkdown

go.mod, go.sum
…github.com/go-git/go-git/v5/plumbing [IDE-855] (#746)"
This reverts commit a03d6c33e18ecfb066f8c27e89688c6adc78281a.
This is just to include previous changes in CLI without this package update.
go-git will be updated in the next PR.
[IDE-855]: https://snyksec.atlassian.net/browse/IDE-855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: revert 746

infrastructure/code/snyk_code_http_client.go, infrastructure/code/snyk_code_http_client_test.go, infrastructure/code/types.go
This is sending the IDE name and version and the extension name and version to autofix requests and feedback events.
This is for analytics purposes. IDE extensions might support different features at a given point in time and knowing the extension used helps knowing what features are available to the end user.
=> feat: Sending IDE+extension versions to autofix

infrastructure/code/constants.go, infrastructure/code/fake_snyk_code_api_service.go, infrastructure/code/issue_enhancer.go, infrastructure/code/issue_enhancer_test.go
When the user triggers the issue action in code, no user event was sent for analytics. This addresses it by sending a FIX_APPLIED event.
EDIT: Using the existing event type FIX_APPLIED for simplicity.
=> feat: Sending a user event when fixing inside the editor

infrastructure/utils/fingerprint.go
OSS Issues reported for "pip" package manager have base directory in the data-flow, this interferes with the logic making hashing inconsistent and relative to the directory which is not relevant in this case.
Example data flow: `pip-goof@0.0.0 > flask@1.0.2 > werkzeug@2.1.2`
In this case, **pip-goof** should not be included as part of the **string** to be **hashed** because the same issue coming from a different directory will have a different hash 
(eg: when we do delta scanning, the base branch will be cloned in a `tmp` directory and scanned, this will result in the hash to always be different for all OSS "pip" issues.
=> fix: fix issue metadata used for hashing [IDE-816]

infrastructure/oss/range_finder.go
```
goroutine 44 [running]:
github.com/snyk/snyk-ls/infrastructure/oss.getDependencyNode(_, {_, _}, {{0xc0001588d0, 0x25}, {0xc000179a40, 0x15}, {0xc0001799f8, 0x17}, {0xc0049006e8, ...}, ...}, ...)
/mnt/c/users/shawky/work/snyk-ls/infrastructure/oss/range_finder.go:76 +0xa12
github.com/snyk/snyk-ls/infrastructure/oss.convertScanResultToIssues(0xc000d3dc08, 0xc004328a48, {0xc0001590e0, 0x1f}, {0xc007d37900, 0x116f, 0x1170}, {0x30a7bb0, 0xc0007ec640}, {0x30a3870, ...}, ...)
/mnt/c/users/shawky/work/snyk-ls/infrastructure/oss/issue.go:140 +0x325
github.com/snyk/snyk-ls/infrastructure/oss.(*CLIScanner).retrieveIssues(0xc000229ce0, 0xc004328a48, {0xc0001590e0, 0x1f}, {0xc007d37900, 0x116f, 0x1170})
/mnt/c/users/shawky/work/snyk-ls/infrastructure/oss/cli_scanner.go:493 +0x1eb …
```
=> fix: panic because nil dep

domain/snyk/issues.go, infrastructure/code/bundle_uploader.go, infrastructure/code/bundle_uploader_test.go, infrastructure/code/code.go, infrastructure/code/convert.go, infrastructure/code/upload_batch.go, infrastructure/filefilter/filter.go, infrastructure/filefilter/filter_test.go, infrastructure/filesystem/filesystem.go, infrastructure/oss/code_actions.go, infrastructure/oss/issue.go, infrastructure/oss/oss_test.go
* VS sends folderPath with a trailing slash which breaks fileFilter.
* Improve memory usage
=> hotfix: fix fileFilter and reduce memory usage [IDE-926] [IDE-662]

infrastructure/code/code_html.go, infrastructure/code/template/details.html, infrastructure/code/template/scripts.js, infrastructure/code/template/styles.css, infrastructure/iac/template/scripts.js
The logic between IDE's for handling AI Fix functionality is mostly the same, this means having separate scripts in each IDE for this feature also means a lot of duplication and difficulty in maintenance due to different nuances in the implementations.
This PR migrates AI Fix Logic, centralizes it in LS and unifies the logic, allowing injecting only the IDE Specific logic that is absolute necessary.
=> chore: migrate AI Fix JS logic from IDEs to LS [IDE-655]

domain/ide/command/navigate_to_range.go, go.mod, infrastructure/code/autofix.go, infrastructure/code/bundle.go, infrastructure/code/code.go, infrastructure/code/code_test.go, infrastructure/code/issue_enhancer.go, infrastructure/code/issue_enhancer_test.go, infrastructure/code/path.go
The LSP pre-defined message for this is: window/showDocument.
We should encode the Action in a URI, e.g.
`snyk:///Users/basti/workspace/blah/app.js?product=Code%20Quality&issueId=123&action=showInDetailPanel`
Each IDE must intercept the `window/showDocument` message, and if it encounters the snyk scheme in the URI, it must not pass it on to the default handler, but do the appropriate action, in this case open the issue in the product issue detail panel.
For the encoded URI we would need:
- FilePath
- Product
- IssueId
- Action
=> feat: added a new code action and code lens for showDocument

domain/snyk/issues.go, infrastructure/authentication/auth_service_impl.go, infrastructure/authentication/auth_service_impl_test.go, infrastructure/oss/cli_scanner.go, internal/testutil/test_setup.go
- Reset authentication configuration if authentication method does not match the provider, and the API reports a credential problem.
- Retrieve SDK configuration always with the path of the working directory
=> fix: cleanup inconsistent auth configuration when needed [IDE-916]

domain/scanstates/template/details.html
IDE users may have multiple open projects. Snyk scans all of them and reports the scan summary (including deltas) for all open projects.
This could cause confusion where it's not obvious that more than one project is open (especially bad in the JetBrains IDEs, where each project has its own IDE instance, but because those instances share a language server, they also share a scan summary.
This is a pragmatic fix to update the wording in the summary to indicate that the summary totals apply to all open projects. Ideally we would eventually enhance language server to only scan and report on issues for the currently active/foregrounded project, but this requires significant work.
Before
After
=> fix: update scan summary wording to account for users who have multiple open projects [IDE-978]

infrastructure/code/code_html_test.go, infrastructure/code/template/details.html
GO Template conditional statements are used to choose when to render certain elements based on different states for AI Fix (**Error**, **Success**, **Scan In Progress**...)
When Generating an AI Fix, we require values of certain attributes from the HTML Elements which are injected through the 
Go Templating mechanism. Eg. `issue-id` -  if the element holding the attribute is not rendered, the logic will not work.
We rely on `toggleElement` function to toggle the `hidden` and `show` classes to hide/display elements so a better way of working with this mechanism is to use the conditional statements for the `hidden` and `show` class name instead of the element/section itself, this way the element is still available if needed and can be toggled based on scripts.
=> fix: render AI fix elements based on show-hidden class [IDE-1020]

application/di/init.go, application/server/execute_command_test.go, domain/ide/command/code_fix_apply_edit.go, domain/ide/command/code_fix_diffs.go, domain/ide/command/code_fix_diffs_test.go, domain/ide/command/command_factory.go, domain/ide/command/command_service.go, domain/ide/command/command_service_test.go, domain/ide/command/generate_issue_description.go, domain/ide/command/navigate_to_range.go, go.mod, go.sum, infrastructure/code/ai_fix_handler.go, infrastructure/code/ai_fix_handler_test.go, infrastructure/code/code_html.go, infrastructure/code/code_html_test.go, infrastructure/code/code_test.go, licenses/github.com/hashicorp/hcl/go.mod
The DeepCode LLM Binding initializing was moved from `init.go` to avoid further complication with uninitialized components, as of know it is only used in the `ai_fix_handler.go` so it is initialized as it's used.
It will be initialized `WithEndpoint` using the current API Endpoint configured.
=> fix: lazy instantiation deepcode LLM binding 

infrastructure/oss/issue.go, infrastructure/oss/types.go, infrastructure/oss/types_test.go
Issue.DisplayTargetFile had the wrong value if the displayTargetFile exists in a subfolder.
Which broke our cache deduplication logic. Since issues that were included in subfolders had basically DisplayTargetFile value of= root + fileName
This resulted in issues having the same displayTargetFile when they exist in other folders.
This fix will use the pre-calculated affectedFilePAth and will set it's value to issue.DisplayTargetFile.
=> fix: use affectedFilePath as targetFilePath for OSS issues

internal/storedconfig/stored_config.go, internal/storedconfig/stored_config_test.go
When merging git config set precedence of dynamic fields to the config loaded from Config if it exists.
=> fix: git config migration precedence

domain/ide/command/ignores_request.go, domain/ide/command/ignores_request_test.go, infrastructure/code/code_html_test.go, infrastructure/code/template/details.html, infrastructure/code/template/scripts.js
Needed in the IDE scripts for things like submit ignore request, so making it generally available.
Also fixed a bug where the input directory was being stored as `types.FilePath` in the GAF config instead of as the expected `string`.
- None added, just updated.
- N/A
- N/A
- N/A
=> fix: expose issue id for IDE scripts to use [IDE-1127]

go.mod, go.sum, infrastructure/code/fake_code_client_scanner.go
`code-client-go` was recently updated to add the `Upload` method to the `CodeScanner` interface. This PR bumps the version and adds an empty implementation of that method to `FakeCodeScannerClient`.
=> fix: bump code-client-go version, and add Upload implementation

.gitignore, domain/ide/command/copy_auth_link.go, infrastructure/authentication/auth_service.go, infrastructure/authentication/auth_service_impl.go, infrastructure/authentication/auth_service_impl_test.go, infrastructure/authentication/oauth_provider.go
The auth URL is only relevant during authentication. When authentication is triggered, it obtains a write-lock on the authentication service. Thus, the copy auth link command was waiting for authentication to finish until it obtained the now obsolete auth URL.
This fix
- adds a method to the Authentication Service interface and its implementations for retrieving the Auth URL via the provider
- implements the retrieval without usage of any locks
=> fix: copy auth link command should not use read locks

infrastructure/code/code_html.go, infrastructure/code/code_html_inline_ignores_test.go, infrastructure/code/code_html_test.go
- Added unit tests for the updateFeatureFlags method in code_html.go to cover scenarios with VS Code and non-VS Code integrations, and when the feature flag is enabled or disabled.
- Fixed a bug in updateFeatureFlags where the global codeRenderer's inlineIgnoresEnabled field was being updated instead of the instance's field.
=> fix: inline ignores only for vscode [IDE-789]

application/server/server_smoke_test.go
Cleanup smoke test for unmanaged scans and make it run as a smoke test.
=> fix: test for unmanaged scans as smoke test [IDE-850]

internal/uri/fs_case_sensitivity_darwin.go, internal/uri/fs_case_sensitivity_linux.go, internal/uri/fs_case_sensitivity_windows.go, internal/uri/uri_util.go, internal/uri/uri_util_test.go
This PR addresses an issue where workspace folder trust validation
fails on case-insensitive filesystems (Windows and macOS) when comparing paths
with different letter casing.
Key changes:
- Added robust case sensitivity detection logic for different filesystems:
- Windows is always treated as case-insensitive
- macOS is tested by creating temporary files with different case and
comparing inode numbers
- Linux and other systems default to case-sensitive behavior
- Implemented an in-memory cache for filesystem case sensitivity results to
avoid redundant filesystem operations
- Used filesystem root/volume as cache key to correctly handle different
mounted volumes with potentially different case sensitivity settings
- Fixed several edge cases with proper error handling and fallbacks
- Added …
=> fix(uri): implement case-insensitive path checking with in-memory cache [IDE-1198]

.windsurfrules, infrastructure/oss/cli_scanner.go, infrastructure/oss/cli_scanner_test.go
Added unit tests to verify the functionality that removes `--all-projects` parameter from command slice and conditionally adds it back based on parameter conflicts.
The tests cover two main scenarios:
1. Verifying that `--all-projects` is properly removed and then added back when there are no conflicting parameters
2. Verifying that `--all-projects` is not added back when there are conflicting parameters like `--file=package.json`
This ensures the code behaves correctly when handling CLI parameters that are incompatible with `--all-projects`.
=> fix: add unit test for prepareScanCommand's --all-projects removal [IDE-1048]

infrastructure/oss/cli_scanner.go, infrastructure/oss/types.go, internal/uri/uri_util.go, internal/uri/uri_util_test.go
The pull request removes the packageManager check in cli_scanner.go and the packageManagerUnmanaged constant in types.go.
=> fix: remove packageManager check [IDE-1174]

application/server/server.go, go.mod, go.sum, licenses/github.com/cenkalti/backoff/v5/LICENSE, licenses/github.com/patrickmn/go-cache/LICENSE, ls_extension/main.go, ls_extension/main_test.go
This PR ensures to make use of the GAF configuration cache and set it to 30 seconds. This improvement shall reduce the execution of more cost excessive functions when accessing configuration values and is aligned with existing caching of authentication data.
=> chore: Enable 30s config cache

application/server/server.go
Add `snyk-ls-` prefix to `x-snyk-ide` header. 
Backend requires this prefix 
Also add X-Snyk-CLI-Version header back, since current version checking in registry will break for LS  and it will prioritize checking for the CLI header, if it exists first
This is a temp workaround until the backend logic is fixed. Also this change basically reverts the headers change to how it was before.
=> fix: add snyk-ls- prefix to x-snyk-ide header [IDE-1244]

README.md, application/server/execute_command.go, application/server/execute_command_test.go, application/server/server.go, domain/ide/command/code_fix_apply_edit.go, domain/ide/command/code_fix_diffs.go, domain/ide/command/code_fix_feedback.go, domain/ide/command/execute_mcp.go, domain/ide/command/workspace_folder_scan.go, domain/ide/command/workspace_scan.go, infrastructure/authentication/auth_service_impl.go, internal/testsupport/helpers.go
`$/cancelRequest` support. See JRPC2 docs [here](https://pkg.go.dev/github.com/creachadair/jrpc2#hdr-Contexts_and_Cancellation).
Currently only for the login command.
Also, snuck in a change to make logouts cancel a previous login request.
- UT only, should proably do an integration test, maybe later.
- N/A
=> feat: allow command cancelling [IDE-962]

domain/ide/command/ignores_request.go, go.mod, go.sum
From our [E2E test](https://snyksec.atlassian.net/wiki/spaces/CLI/pages/3339747813/E2E+Tests) meeting it was decided that the `--expiration` flag for the ignore create workflow should take the value `never` for ignores that don't have an expiration date, instead of allowing an empty string like it was previously used. 
This [GAF PR](https://github.com/snyk/go-application-framework/pull/343) added this [change](https://github.com/snyk/go-application-framework/pull/350/commits/746f2ed0c96e8e786dbca8bf0f92abf1107b0b70#diff-489229b85a1c04519bb0ee241858ce475b4d87c3f7c95d1f1ec31ac5dd673f09L229-L234) to the ignore workflow, and some other presentation changes for the CLI. The changes to the `ignore_request.go` just map the new ignore expiration input value to the new requirement.
=> chore: update ignore never expire value

infrastructure/code/code_html.go, infrastructure/code/code_html_test.go, infrastructure/code/template/details.html, infrastructure/code/template/scripts.js
"Expiration" "Do not expire" should be "Never".
Status should match the web UI e.g. (`underReview` should be "Pending")
- N/A
- N/A
- N/A
=> fix: update IAW wording to match web UI [IDE-1151]

internal/storedconfig/git.go, internal/storedconfig/git_test.go, internal/storedconfig/stored_config_test.go
When a git repository doesn't contain either a "main" or "master" branch, the `storedconfig` package fails to populate local branches in the folder configuration. This happens because `getFromGit()` returns an error when it cannot determine a base branch, causing the entire git configuration retrieval to be treated as a failure.
The issue occurs in `internal/storedconfig/git.go`:
- `getFromGit()` successfully retrieves local branches
- `getBaseBranch()` returns an error when neither "main" nor "master" exist
- This error causes `getFromGit()` to return the error alongside the partially populated `FolderConfig`
- `GetOrCreateFolderConfig()` treats any error from `getFromGit()` as a complete failure and discards the git information
Modified `getFromGit()` to handle base branch determination …
=> fix: populate local branches even when base branch cannot be determined [IDE-1238]

application/server/configuration.go, infrastructure/analytics/analytics.go, infrastructure/authentication/auth_service_impl.go
Simplified Analytics Event Creation - Event creation now supports creating a target ID for a particular file, or for an instance of the Language server. This means that places in the code that send analytics just need to call the helper method to create a new event, then add their specific extension field.
Added analytics for Org changes: Uses the new mechanism to create an analytics event, then populates the extension with the old and new org values. Note that we use the Org UUIDs rather than the slug names.
=> feat: send analytics on org change [IDE-880]

application/server/server_test.go
`Test_textDocumentDidOpenHandler_shouldPublishIfCached` had the logical operation precedent wrong and wasn't waiting long enough.
Example: https://github.com/snyk/snyk-ls/actions/runs/16751012822/job/47422442770?pr=953
- Test fixed.
- N/A
- N/A
- N/A
=> fix(test): flaky server test

domain/ide/codelens/codelens_test.go, domain/ide/command/execute_cli_test.go, infrastructure/cli/cli_fake.go, infrastructure/cli/initializer_test.go, infrastructure/iac/iac_html_test.go, infrastructure/iac/iac_test.go, infrastructure/oss/cli_scanner_test.go, infrastructure/oss/oss_test.go, infrastructure/oss/vulnerability_count_test.go, internal/testutil/test_setup.go
Instead rely on the config reference already in the tests.
This is part 4, the majority was done previously.
Mainly made the fake CLI not use `CurrentConfig()` and removed usage in `test_setup.go`
- Test amended and all pass.
- N/A
- N/A
- N/A
=> refactor(test): reduce usage of `CurrentConfig()` [IDE-1314]

.github/workflows/update-compatibility-matrix.yaml
Attempt 2, because I missed a path in attempt 1.
- N/A
- N/A
- N/A
- N/A
- N/A
=> chore(ci): correct docs sync path pt.2 [IDA-563]

mcp_extension/snyk_tools.json
Changing the snyk_code_scan tool description to include the [list of languages](https://docs.snyk.io/supported-languages/supported-languages-list) that Snyk supports. There will be a change in the vscode-extention repo as well that updates the direction of running the snyk_code_scan tool for new first party code that is generated to running the snyk_code_scan tool for new first party code that is generated in a Snyk-supported language.
Jira Ticket: https://snyksec.atlassian.net/browse/AG-4
=> fix(MCP): create new rules for SAST only

application/config/config.go, application/server/configuration.go, application/server/configuration_test.go, infrastructure/cli/cli_extension_executor.go, infrastructure/code/ai_fix_handler_test.go
Function Call Examples:
// User-triggered changes (sends analytics)
UpdateSettings(c, params.Settings, "user", true)
// Initialization (no analytics)
writeSettings(c, settings, true, "", false)
// Tests (sends analytics)
UpdateSettings(c, settings, "test", true)
Analytics Event Format:
```
{
"interaction": {
"type": "Config changed",
"targetId": "pkg:filesystem/path/to/folder",
"extension": {
"config::organization::oldValue": "oldOrg",
"config::organization::newValue": "newOrg",
"config::organization::triggerSource": "user"
}
}
}
```
=> feat: add config analytics [IDE-1475]
