application/config/automatic_config.go, application/config/automatic_config_test.go, go.mod, go.sum, infrastructure/cli/cli.go
=> fix: don't use path to set default java home [ROAD-1167]

.github/setup_aws_credentials.py, .github/workflows/release.yaml
This replaces the previous authentication with the newly recommended mechanism based on OIDC tokens.
https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services
=> chore: Login to AWS with an OIDC federated identity

.gitignore
=> fix: add webidentity.json to .gitignore

.github/setup_aws_credentials.py, .github/workflows/release.yaml
=> fix: specify webidentity file with absolute path, remove `--rm-dist`

.github/workflows/release.yaml
=> fix: reinstate `--rm-dist`

.github/workflows/release.yaml
=> chore: update goreleaser, move aws login below cleanup

.github/workflows/release.yaml
=> fix: use absolute path for webidentity token file

.github/setup_aws_credentials.py, .github/workflows/release.yaml
=> fix: open webidentity file with 'x' parameter for creating and writing

.github/workflows/release.yaml
=> fix: move login back down to verify file is not deleted during steps

.github/setup_aws_credentials.py
=> fix: remove quotes in github env

domain/ide/initialize/initializer.go, domain/snyk/auth_provider.go, domain/snyk/auth_service.go, domain/snyk/scanner.go, infrastructure/cli/auth/initializer.go, infrastructure/cli/auth/initializer_test.go, infrastructure/cli/auth/provider.go, infrastructure/cli/auth/provider_fake.go, infrastructure/cli/cli.go, infrastructure/cli/initializer.go, infrastructure/cli/initializer_test.go, infrastructure/oss/oss_integration_test.go, infrastructure/services/auth_service.go
Sends a message when the user is not authenticated.
=> feat: handle invalid user tokens [ROAD-1059]

.github/workflows/build.yaml, .github/workflows/instance-tests.yaml, Makefile, application/server/server_test.go
Instance tests allow to run a smoke test against a Snyk Cloud Instance
=> chore: add instance tests [ROAD-1209]

infrastructure/cli/initializer.go
Always repost CLI path notification when found.
=> fix: always send CLI path notification

.github/workflows/release.yaml
=> chore: update release workflow actions to v3 due to deprecation of node runner in github

infrastructure/cli/auth/initializer.go, infrastructure/cli/cli.go, infrastructure/cli/initializer.go, infrastructure/code/code.go, internal/notification/notification.go
Ensure we always pass type of a message.
=> fix: always pass message params

infrastructure/cli/install/downloader.go
=> fix: remove artificial delay

.github/workflows/release.yaml
Allow for manual release dispatch
=> feat: allow manual release dispatch

.github/workflows/release.yaml
=> fix: goreleaser version

application/config/config.go, application/server/configuration.go, application/server/configuration_test.go, application/server/server.go, domain/ide/converter/converter.go, domain/ide/workspace/folder.go, domain/ide/workspace/folder_test.go, domain/ide/workspace/workspace.go, domain/snyk/issues.go, domain/snyk/product.go, domain/snyk/scanner.go, domain/snyk/scanner_recorder.go, domain/snyk/scanner_test.go, domain/snyk/test_product_scanner.go, go.mod, go.sum, infrastructure/code/code.go, infrastructure/code/convert.go, infrastructure/code/convert_test.go, infrastructure/iac/iac.go, infrastructure/oss/scanner.go, internal/product/product.go, licenses/github.com/puzpuzpuz/xsync/LICENSE
Disabling a product in settings now removes the previously published diagnostics of that product
=> [ROAD-1235] fix: remove diagnostics when product disabled

application/config/config.go, application/config/config_test.go, application/server/configuration.go, application/server/configuration_test.go, application/server/lsp/message_types.go, application/server/server_test.go, domain/ide/hover/fake_service.go, domain/ide/workspace/folder.go, domain/ide/workspace/folder_test.go, internal/testutil/test_setup.go
_This PR should implement filtering based on severity._
=> feat: severity setting [ROAD-1143]

application/server/lsp/message_types.go, application/server/server.go, domain/ide/workspace/folder.go, domain/ide/workspace/workspace.go, infrastructure/iac/errors.go, infrastructure/iac/iac.go
Ignore the error about not finding IAC files
=> feat: Silence IaC error [ROAD-1142]

.github/workflows/build.yaml, README.md, application/config/config.go, application/server/configuration.go, application/server/configuration_test.go, application/server/lsp/message_types.go, application/server/server_test.go, domain/snyk/issues.go, domain/snyk/scanner.go, domain/snyk/scanner_test.go, infrastructure/code/backend_service_test.go, infrastructure/code/code.go, infrastructure/code/code_test.go, infrastructure/code/convert.go, infrastructure/code/convert_test.go, infrastructure/code/dataflow.go
=> feat: enable separate configuration of Snyk Code Quality and Snyk Code Security issues and filter reporting

.github/workflows/build.yaml, .github/workflows/release.yaml
=> fix: deactivate verify analytics to fix release flow

application/config/config.go, application/server/server.go, application/server/server_test.go, domain/ide/codeaction/codeaction_test.go, domain/ide/codelens/codelens_test.go, infrastructure/cli/initializer.go, infrastructure/cli/install/installer.go, internal/testutil/test_setup.go
tests needed some clean up, as some were expecting, or were affected by results from previously executed tests
Also added some debug logging
=> fix: tests with fake cli installer

application/config/config.go, application/server/configuration.go, application/server/configuration_test.go, application/server/lsp/message_types.go, infrastructure/amplitude/client.go, infrastructure/amplitude/client_test.go, infrastructure/amplitude/install_event_test.go
Add runtime information to analytics, enable LS to receive it via initializationOptions
=> feat: ✨ add runtime information to analytics [ROAD-1179]

.github/workflows/build.yaml, Makefile, ampli.json
Verifies event tracking implementation in source code as part of CI. The token added is a personal access token generated in https://data.amplitude.com/snyk/Snyk/settings/api-tokens
=> feat: verify analytics within CI

infrastructure/snyk_api/snyk_api.go
Fixes a panic that occurs when the connection returns an error
=> fix: panic when connection fails [HEAD-80]

application/server/configuration.go, application/server/execute_command.go, application/server/server.go, main.go
Small refactor, changing some functions to private
=> refactor: change handlers to private

infrastructure/code/bundle.go, infrastructure/code/code.go, infrastructure/code/code_test.go
Error is currently not propagated to custom UI, since we don't return it in some scenarios. This PR fixes it to ensure users don't get success, when an analysis error occurs.
=> fix: propagate error from Snyk Code [HEAD-9]

README.md
Added docs for the `scanningMode` option
=> [HEAD-12] Add docs for scanningMode

application/command/command_service.go, application/command/command_service_test.go, application/di/init.go, application/server/notification.go, application/server/notification_test.go, application/server/server.go, application/server/server_test.go, domain/ide/codeaction/codeaction_test.go, domain/ide/codelens/codelens.go, domain/ide/codelens/codelens_test.go, domain/ide/command/open_browser.go, domain/ide/converter/converter.go, domain/snyk/command.go, domain/snyk/message.go, infrastructure/code/code.go, infrastructure/code/code_test.go, infrastructure/code/convert_test.go, infrastructure/code/dataflow.go, infrastructure/code/fake_snyk_code_api_service.go, infrastructure/code/settings.go, infrastructure/code/settings_test.go, infrastructure/iac/iac.go, infrastructure/oss/issue.go, internal/data_structure/ordered_map.go, internal/data_structure/ordered_map_test.go, internal/notification/notification_types.go
This PR provides ability for users to enable Snyk Code, when it's disabled in their organization settings.
=> feat: allow users to enable Snyk Code when disabled by org [HEAD-66]

infrastructure/code/convert.go, infrastructure/code/convert_test.go
Fix off-by-one error that was a regression as part of https://github.com/snyk/snyk-ls/pull/217
=> fix: off-by-one for reported code issues

.github/workflows/instance-tests.yaml
Temporarily removes unavailable instance, see https://snyk.slack.com/archives/C04HYFBCZPU/p1675935045061609
=> refactor: temporarily remove unavailable instance

Makefile, README.md, infrastructure/code/backend_service.go, infrastructure/code/backend_service_pact_test.go, infrastructure/code/pacts/snykls-snykcodeapi.json, install.sh
https://snyksec.atlassian.net/browse/ZEN-357
feat: snyk code analysis with specific org header
Token validation logic inside deeproxy and registry expect this header to be set, in order to properly check feature flags and settings of user's org
NOTE: this PR depends on another PR https://github.com/snyk/snyk-ls/pull/229
=> [ZEN-357] feat: snyk code analysis with specific org header

go.mod, go.sum
=> chore: update deps [HEAD-126]

infrastructure/cli/cli.go, infrastructure/code/code.go, infrastructure/code/code_test.go, internal/uri/uri_util.go, internal/util/ignore.go
=> fix: correctly parse sub directory .gitignore files [HEAD-126]

infrastructure/cli/install/installer.go, infrastructure/sentry/sentry_error_reporter_test.go
=> chore: change lockfile timeout to 10 min

infrastructure/code/upload_batch.go
=> fix: reduce http 413 errors by reducing max allowed payload size [HEAD-139]

application/server/server.go
=> fix: check if folder found for file when opening file

application/codeaction/codeaction_test.go
=> chore: remove stale comment [HEAD-161]

application/server/lsp/message_types.go, infrastructure/iac/types.go
_This PR should define an interface for the IaC issue data type_
=> feat: defining interfaces for IaC [HEAD-146]

application/codeaction/codeaction.go, application/codeaction/codeaction_test.go, application/codeaction/handlers.go
Fixed panics when attempting to resolve non-deferred code actions
=> fix: panics on unrelated code actions [HEAD-205]

infrastructure/code/convert.go
Fixup the 386 release of https://github.com/snyk/snyk-ls/pull/234
=> fix: fix the releaser for windows

go.mod, go.sum, infrastructure/code/code.go, infrastructure/code/code_test.go, infrastructure/code/ignores.go, infrastructure/code/ignores_test.go, licenses/golang.org/x/exp/LICENSE
=> feat: parse .snyk ignore rules [HEAD-224]

infrastructure/sentry/sentry_error_reporter.go
=> fix: dereference sentry id

infrastructure/code/code.go, infrastructure/code/code_test.go, infrastructure/code/fake_snyk_code_api_service.go, infrastructure/code/ignores_test.go, internal/testutil/files.go
This PR fixes ignore files not being respected in different work directories.
=> fix: ignore with several work dirs [HEAD-234]

README.md, application/config/config.go, application/server/configuration.go, application/server/configuration_test.go, infrastructure/code/backend_service.go, infrastructure/code/backend_service_interface.go, infrastructure/code/backend_service_pact_test.go, infrastructure/code/fake_snyk_code_api_service.go, internal/lsp/message_types.go
=> chore: make deeproxy URL configurable [HEAD-253]

README.md, application/config/config.go, application/di/init.go, application/server/execute_command_test.go, application/server/server.go, domain/ide/command/command_factory.go, domain/ide/command/oauth_refresh.go, domain/ide/command/oauth_refresh_test.go, domain/snyk/command.go, go.mod, go.sum
=> feat: implement token refresh command [HEAD-238]

application/config/config.go, application/server/configuration.go, go.mod, go.sum, infrastructure/cli/auth/initializer.go
_This PR should fix some issues discovered when testing oauth support in our Eclipse plugin._
=> fix: oauth support

infrastructure/code/convert.go, infrastructure/code/convert_test.go
Code lense dataflow navigation was broken, because of the change to relative paths in Snyk Code. 
This fixes it, by joining the baseDir with the relative path.
=> fix: use abs paths for code lenses

go.mod, go.sum
=> chore: update go application framework

application/config/client_settings.go, application/config/client_settings_test.go, application/config/config.go, application/server/configuration_test.go, application/server/server_test.go, infrastructure/cli/cli.go, infrastructure/cli/cli_test.go, infrastructure/cli/environment.go, infrastructure/cli/environment_test.go, infrastructure/code/backend_service.go, infrastructure/code/backend_service_pact_test.go, infrastructure/code/convert_test.go, infrastructure/code/pacts/snykls-snykcodeapi.json, infrastructure/snyk_api/pacts/snykls-snykapi.json, infrastructure/snyk_api/snyk_api.go, infrastructure/snyk_api/snyk_api_pact_test.go
* use gaf for getting and setting the organization
* fix user/me url to include v1
=> feat: use gaf configuration for organization

README.md, application/config/config.go, application/server/execute_command.go, application/server/server.go, application/server/server_test.go, domain/ide/command/command_factory.go, domain/ide/command/get_active_user.go, domain/ide/command/get_active_user_test.go, domain/ide/command/oauth_refresh_test.go, domain/ide/command/test_helpers.go, domain/snyk/command.go, infrastructure/services/auth_service.go, infrastructure/snyk_api/fake_api_client.go, infrastructure/snyk_api/snyk_api.go, internal/lsp/lsp_logger.go
=> feat: add getActiveUserCommand [HEAD-114]

infrastructure/code/bundle.go, infrastructure/code/code_test.go, infrastructure/code/settings.go
Enables Autofix by default for all users. [Additional enablement](https://github.com/snyk/snyk-ls/blob/cc87526238f4ba3a8619a2acd91a75fa4fef0164/infrastructure/code/bundle.go#L196) happens through `/filters` endpoint payload.
=> feat: prepare Autofix release

infrastructure/code/code.go, infrastructure/filefilter/filter.go, infrastructure/filefilter/filter_benchmark_test.go, infrastructure/filefilter/filter_test.go
Optimized Code scans by skipping ignored folders.
=> fix: skip ignored folders in ignore pattern matching

infrastructure/snyk_api/pacts/snykls-snykapi.json, infrastructure/snyk_api/snyk_api_pact_test.go
Fixes Pact contracts not regenerated in #301 
=> fix: pact for sast api

infrastructure/cli/install/downloader.go
previously a non empty content-length header was required for progress reporting.
=> fix: don't require content length header in CLI download [HEAD-332]

application/codeaction/codeaction.go, application/server/execute_command.go, application/server/notification.go, application/server/notification/scan_notifier_test.go, application/server/notification_test.go, application/server/server.go, application/server/server_test.go, domain/ide/codelens/codelens.go, domain/ide/codelens/codelens_test.go, domain/ide/command/code_fix.go, domain/ide/command/code_fix_test.go, domain/ide/command/command_factory.go, domain/ide/issues_provider.go, domain/snyk/command.go, domain/snyk/issues.go, infrastructure/cli/auth/initializer.go, infrastructure/code/bundle.go, infrastructure/code/code_test.go, infrastructure/code/convert.go, infrastructure/code/convert_test.go, infrastructure/code/dataflow.go, infrastructure/code/fake_snyk_code_api_service.go, infrastructure/code/sast_enabled.go, infrastructure/code/sast_enabled_test.go, internal/lsp/message_types.go
Introduces CodeLens for Autofix, replacing data flow one.
=> feat: introduce Autofix codelens [ZEN-607]

domain/ide/command/code_fix.go
Fixes null dereference when finding fix codeaction and some codeactions not setting code action identifier.
=> fix: null dereference in snyk.code.fix

application/config/config.go, application/server/configuration_test.go, application/server/notification.go, application/server/notification_test.go, application/server/server_test.go, domain/ide/codelens/codelens_test.go, internal/lsp/message_types.go
After publishing new diagnostics, we need to update code lenses, too.
=> fix: refresh code lenses after publishing diagnostics

application/codeaction/codeaction.go, application/codeaction/codeaction_test.go, application/di/init.go, application/di/test_init.go, application/server/execute_command.go, application/server/notification_test.go, application/server/server.go, application/server/server_test.go, domain/ide/command/code_fix_feedback.go, domain/ide/command/code_fix_feedback_test.go, domain/ide/command/command_factory.go, domain/snyk/command.go, infrastructure/cli/auth/initializer.go, infrastructure/code/backend_service.go, infrastructure/code/backend_service_interface.go, infrastructure/code/bundle.go, infrastructure/code/bundle_test.go, infrastructure/code/convert.go, infrastructure/code/fake_snyk_code_api_service.go, infrastructure/code/sast_enabled.go, infrastructure/code/sast_enabled_test.go, infrastructure/code/types.go
Asks for user feedback when successful fix is provided for Snyk Code results.
Example feedback request message:
=> feat: request user feedback on Autofix [ZEN-635]

infrastructure/code/bundle.go, infrastructure/code/bundle_test.go
Fixes shard key calculation for Code analysis. Matches [the calculation logic from CLI](https://github.com/snyk/code-client/blob/bf87e112012fac006aaf1e153b836f8fab518aa5/src/analysis.ts#L319).
=> fix: code shard key calculation

application/config/config.go, application/config/config_test.go
Increases the analysis timeout from 10 min to 12h
=> chore: increase Snyk Code analysis timeout

Makefile, application/server/server_test.go
25 min timeout is right now not enough to pass smoke tests
=> chore: increase test time-out further

infrastructure/oss/vulnerability_count.go, infrastructure/oss/vulnerability_count_test.go
Service groups and counts issues and forwards them to a given processor function
=> feat: introduce vulnerability count service [HEAD-280]

README.md, application/di/init.go, application/di/test_init.go, application/server/inline_values.go, application/server/inline_values_test.go, application/server/notification.go, application/server/server.go, application/server/server_test.go, domain/ide/converter/converter.go, domain/ide/hover/service.go, domain/snyk/inline_value.go, domain/snyk/provider_fake.go, domain/snyk/range.go, domain/snyk/scanner.go, domain/snyk/scanner_test.go, domain/snyk/test_product_scanner.go, infrastructure/oss/inline_value.go, infrastructure/oss/oss.go, infrastructure/oss/oss_integration_test.go, infrastructure/oss/vulnerability_count.go, infrastructure/oss/vulnerability_count_test.go, internal/lsp/message_types.go
=> feat: provide vulnerability count as inline value on Open Source scan

go.mod, go.sum
... through updating the application framework
=> fix: Use correct env var for integration environment name

application/config/config.go, application/server/server.go, go.mod, go.sum, infrastructure/cli/environment.go, infrastructure/cli/environment_test.go
Use application framework to generate a common user-agent header. This includes filling fields consistently.
=> fix: Use common function to generate user-agent

application/server/configuration.go, application/server/configuration_test.go
* Correctly append path
* Use original path to append, so that a path can also be removed
=> fix: Custom path configuration

.github/CODEOWNERS
Adding team Nebula as code owners for files that could break local-engine
=> chore: adding Nebula as lce GH owners [NEBULA-1290]

.github/upload-to-s3.sh, .github/workflows/build.yaml, .github/workflows/release.yaml, .goreleaser.yaml
Uploads artifacts to S3 and checks afterwards, whether the upload was successful by downloading each file and checking it against the published checksum.
=> chore: upload artifacts via aws cli and verify upload [HEAD-452]

go.mod, go.sum
For future use of oauth, update the token urls, through updating GAF
=> chore: update oauth urls

infrastructure/iac/iac.go, infrastructure/iac/iac_test.go, infrastructure/iac/testdata/RBAC-iac-result-invalid-path.json
=> fix: conversion of numerical path entries in IAC [HEAD-614]

infrastructure/learn/service.go
Filtering by CVEs was incorrect, this is fixed now
=> fix: snyk learn lessons filtering [HEAD-558]

domain/snyk/issues.go, infrastructure/code/backend_service.go, infrastructure/code/bundle.go, infrastructure/code/code_test.go, infrastructure/code/convert.go, infrastructure/code/fake_snyk_code_api_service.go, infrastructure/code/sarif_types.go, infrastructure/code/settings.go
Use SARIF property to determine if a certain issue is autofixable instead of relying on filters endpoint.
Do not merge until https://github.com/snyk/sast-analysis-api/pull/455 is through.
=> refactor: use isAutofixable for Autofix [ZEN-707]

.dcignore, .github/workflows/build.yaml
Using a different secret for the license job.
=> chore: update workflow to use HAMMERHEAD_GITHUB_PAT_SNYKLS secret instead of PAT_BASTI

application/config/config.go, application/config/config_test.go
Ensure that internal config and GAF config make use of the analytics/telemetry settings.
=> fix: consistent telemetry setting [HEAD-730]

.idea/codeStyles/Project.xml, .idea/codeStyles/codeStyleConfig.xml, .idea/copyright/profiles_settings.xml, .idea/copyright/snyk_apache.xml
This adds the codestyle settings from goland to the repo.
=> chore: add goland settings to repo

application/server/server.go, application/server/server_test.go, go.mod, go.sum, internal/lsp/lsp_logger.go, licenses/github.com/fatih/color/LICENSE.md, main.go
Shutdown was stalling, as was exit. This makes the shutdown async and adds a test for shutdown
=> fix: shutdown & exit requests/notifications [HEAD-750]

application/config/config.go, application/config/config_test.go, go.mod, go.sum
Use central logic the application framework provides to retrieve IsFedramp().
=> chore: use gaf for isFedramp

go.mod, go.sum
Update the vulnerable dependency gomarkdown
=> fix: upgrade vulnerable dependency gomarkdown

application/server/configuration.go, domain/ide/command/sast_enabled.go, domain/ide/command/sast_enabled_test.go, domain/snyk/authentication_functions.go, licenses/github.com/hashicorp/hcl/go.mod
This adds a few guards & sanity checks to improve reliability.
=> fix: sanity checks and guards to improve reliability [HEAD-779]

go.mod, go.sum, infrastructure/code/backend_service.go, infrastructure/code/backend_service_pact_test.go
Update GAF to centrally set the Session-Token Authentication Header. Removed the local logic to clean up the code.
=> feat: centrally set Session-Token [HEAD-884]

infrastructure/code/backend_service.go
_This PR should fix the broken code description URL users see on code hovers._
=> fix: broken updateCodeDescriptionURL url link

domain/ide/workspace/folder.go, domain/ide/workspace/folder_test.go, domain/snyk/scan_result_processor.go
This PR counts issue's severities per product to enhance analytics and reporting.
=> fix: count severity by product [HEAD-879]

infrastructure/analytics/pact_test.go, infrastructure/analytics/pacts/snyk-ls-analyticsprovider.json
This PR add Contract Testing between Report Analytics and Language Server
=> feat: initial report analytics contract testing [HEAD-879]

go.mod, go.sum
=> feat: update go-application-framework to fb50b21

infrastructure/code/backend_service.go
The URL for code descriptions has changed once more. This PR updates it, using https://docs.snyk.io/scan-using-snyk/snyk-code/snyk-code-security-rules
It also fixes a small amount of code smells.
=> fix: update code description URL for code security issues [HEAD-1046]

Makefile, domain/ide/workspace/folder.go, domain/snyk/authentication_functions.go, go.mod, go.sum, infrastructure/analytics/analytics.go, infrastructure/analytics/pact_test.go, infrastructure/analytics/pacts/snyk-ls-analyticsprovider.json
The workflow now requires the experimental flag to be set.
=> refactor: add experimental flag to analytics workflow invocation

infrastructure/oss/vulnerability_count.go
=> chore: 💄remove most severe vuln information from inline value text [HEAD-1063]

application/config/config.go, application/server/configuration.go, application/server/configuration_test.go, domain/ide/command/report_analytics_test.go, domain/ide/workspace/folder.go, domain/ide/workspace/folder_test.go, infrastructure/analytics/analytics.go, infrastructure/analytics/pact_test.go, internal/lsp/message_types.go, licenses/github.com/hashicorp/hcl/go.mod
=> feat: enable analytics [IDE-17]

.circleci/config.yml, .github/CODEOWNERS, catalog-info.yaml
=> chore: switch codeowner to IDE

.github/workflows/instance-tests.yaml
=> chore: added hourly cron schedule to instance tests

infrastructure/code/code.go, infrastructure/code/code_test.go, infrastructure/snyk_api/snyk_api.go, infrastructure/snyk_api/snyk_api_pact_test.go
We need the absolute path for testing and the API call is incorrect.
=> fix: use absolute path [IDE-172]

README.md, application/server/server.go, application/server/server_test.go, domain/ide/command/command_factory.go, domain/ide/command/get_feature_flag_status.go, domain/ide/command/get_feature_flag_status_test.go, domain/ide/workspace/folder.go, domain/snyk/command.go, infrastructure/code/snyk_code_http_client.go, infrastructure/snyk_api/snyk_api.go
=> feat: add Feature Flag command [IDE-171]

application/server/notification/scan_notifier.go, application/server/notification/scan_notifier_test.go, domain/snyk/issues.go, go.mod, go.sum, infrastructure/code/code.go, infrastructure/code/code_test.go, infrastructure/code/convert.go, infrastructure/code/convert_test.go, internal/lsp/message_types.go
Starts using `code-client-go` after https://github.com/snyk/code-client-go/pull/8 gets merged. Also prepares the data for ignored findings to be consumed by IDEs. 
Test it by:
- uncommenting the replace directive, 
- running `make build-debug`,
- adding a replace directive for `snyk-ls` and `code-client-go` in the CLI in the `cliv2` folder
- running `make build` from the CLI 
- running the IntelliJ plugin in debug mode
=> feat: add ignore details [IDE-176]

application/di/init.go
LS initialization was taking to long in edge cases.
=> fix: initialize binary locations in background

infrastructure/code/code_html.go, infrastructure/code/code_html_test.go, infrastructure/code/template/details.html
This PR is a continuation from  [feat: add code template #473](https://github.com/snyk/snyk-ls/pull/473), where we introduced the HTML scaffold for the **Issue Code Panel**.
The goal of this change is to migrate the **IntelliJ UI** for the Issue Code Panel to the **Language Server**. With this PR, we have replicated the following elements:
- The header of the panel, displaying the **title**, **icon**, and **vulnerability type**.
- The **description** of the vulnerability type.
- **Data Flow** section.
- **External Example Fixes** section.
1. Capture the **HTML** from Language Server logs in `getDetailsHtml()`
<details>
<summary>2. Place the **body** in the following index.html: ⬇️</summary>
```html …
```
=> feat: add HTML template for Code Issue panel [IDE-180]

infrastructure/code/code_html.go, infrastructure/code/code_html_test.go, infrastructure/code/template/details.html
This change adds the styles for the links to CWEs
=> chore: style CWE links [IDE-215]

application/di/init.go, go.mod, go.sum, infrastructure/code/code_html.go, infrastructure/code/code_html_test.go, infrastructure/code/template/details.html
Fixes some of the simple styling issues found in https://snyksec.atlassian.net/browse/IDE-227. It also adds some code for edge cases, such as no CWEs (in the case of Code Quality findings) and no example fixes found. Verified in IntelliJ.
The only obvious difference still left is that the font of the code is different but the designs provided [here](https://www.figma.com/file/hcI2QHUtHfcIjgrpYlMqff/Holistic-Ignores?node-id=1637%3A75126&mode=dev) ask for this font.
There are still some differences that aren't fixed, see the bugs in https://snyksec.atlassian.net/browse/IDE-164 to double-check.
I also tidied up the CSS a bit so there's less duplication and the blocks are ordered by the order they're in the HTML.
🚨After having merged, please update the CLI go.mod to pull in latest language …
=> fix: the style for suggestion panel html [IDE-227]

application/di/init.go, go.mod, go.sum, infrastructure/code/fake_snyk_code_api_service.go
Updates the `code-client-go` library and picks up the logging improvements and function options pattern changes.
=> refactor: use function options pattern

infrastructure/code/template/details.html
This PR removes hardcoded color definitions to rely on CSS variables for better theme adaptability. The variables are expected to be provided by the environment in which the LSP is run, ensuring consistent theming that matches the platform.
See related PR in the IntelliJ plugin: [snyk-intellij-plugin#521](https://github.com/snyk/snyk-intellij-plugin/pull/521).
|🌒 Dark|☀️ Light|🧛‍♀️ Darcula|
|-|-|-|
|![dark-theme](https://github.com/snyk/snyk-intellij-plugin/assets/1948377/e96443d5-d6b1-49ee-bcd4-c8420d4ec5cd)|![light-theme](https://github.com/snyk/snyk-intellij-plugin/assets/1948377/721bbe62-1947-453d-b03e-94474a11b439)|![darcula-theme](https://github.com/snyk/snyk-intellij-plugin/assets/1948377/46e9ba1b- …
=> refactor: improve theming for HTML templates [IDE-269]

go.mod, go.sum
Includes the fix in https://github.com/snyk/code-client-go/releases/tag/v1.6.2
=> fix: update code-client-go and fix consistent ignores flow

Makefile
=> chore: update instance test to curl the new Eclipse update site

infrastructure/code/code_html.go, infrastructure/code/code_html_test.go, infrastructure/code/template/details.html
This PR updates the Code Issue panel template to render the data in three columns.
>[!NOTE]
>Styling will be addressed by #522
https://github.com/snyk/snyk-ls/assets/1948377/beba2503-6664-42e1-bb77-a0345e95eb6c
=> feat: display Code Issues information in tabs [IDE-271]

infrastructure/code/code_html_test.go, infrastructure/code/template/details.html
Adds an `ideScript` to inject into.
=> feat: vscode script for html [IDE-375] [IDE-367]

infrastructure/analytics/analytics.go
Adding a comment explaining how some errors are handled in cases where the endpoint is not available when called. 
=> tidy: add explaining comment [IDE-418]

.github/create-cli-pr.sh, .github/workflows/build.yaml, .github/workflows/create-cli-pr.yaml, .github/workflows/release.yaml
This adds automation for creating a CLI PR on releasing language server. It also provides a script that can be triggered manually to create a PR with the latest released LS version.
=> feat: create script / workflows for automatic PR creation

.github/create-cli-pr.sh, .github/workflows/create-cli-pr.yaml, .github/workflows/release.yaml
=> fix: specify secrets correctly

.github/create-cli-pr.sh
=> feat: enable auto-merge on CLI PRs

.github/create-cli-pr.sh
=> feat: add commits in PR body

.github/create-cli-pr.sh, .github/workflows/create-cli-pr.yaml
=> fix: revert breaking linter changes

.github/create-cli-pr.sh
=> fix: no exit 0

.circleci/config.yml
Add quality gates for CircleCi
=> chore: add secret scan to circleci pipeline

.github/workflows/build.yaml
Remove redundant snyk scan from workflows.
=> chore: remove snyk scan from github workflows

domain/ide/workspace/folder.go
Tidy task to clean up the function that builds the analytics event.
=> tidy: reorganise the function that builds the analytics event (IDE-474)

domain/snyk/issues.go, infrastructure/oss/testdata/policyAnnotationsInputData.json, infrastructure/oss/testdata/policySeverityChangeInputData.json, infrastructure/oss/types.go, infrastructure/oss/types_test.go
=> feat: add json mapping

infrastructure/oss/issue_html.go, infrastructure/oss/issue_html_test.go, infrastructure/oss/template/details.html
This will change the text to a link everywhere but it's needed for IntelliJ specifically.
=> feat: add link to cvss score [IDE-285]

infrastructure/oss/issue_html.go, infrastructure/oss/issue_html_test.go, infrastructure/oss/template/details.html
This change accommodates the following cases:
- Severity Change with user notes
- Just annotations notes reason
- Just annotations user notes
- Annotations with notes and user notes
|Note Reason|User Note|Severity Change|Annotations|
|-|-|-|-|
|<img width="1105" alt="just-note-reason" src="https://github.com/snyk/snyk-ls/assets/1948377/8e88b328-eee1-45d7-b8bc-649f2e9d5b64">|<img width="1105" alt="just-user-note" src="https://github.com/snyk/snyk-ls/assets/1948377/b5eccd09-4ec5-44da-86cc-401e2512df4b">|<img width="1105" alt="severity-change-with-reason" src="https://github.com/snyk/snyk-ls/assets/1948377/95bdbc11-8b75-4f70-9786-b93d9054f63d">|<img width="1105" alt="annotations" …
=> chore: conditional render policy details [IDE-454]

infrastructure/code/code_html.go, infrastructure/code/code_html_test.go, infrastructure/code/code_test.go, infrastructure/code/convert.go, infrastructure/code/convert_test.go, infrastructure/code/fake_code_client_scanner.go
This PR improves the handling and formatting of expiration dates to ensure they are displayed correctly in the UI. 
|Before|After|
|-|-|
|<img width="1282" alt="image" src="https://github.com/snyk/snyk-ls/assets/1948377/0e062104-ba04-4744-b2ce-f15b2e0954bf">|<img width="1282" alt="image" src="https://github.com/snyk/snyk-ls/assets/1948377/7dd2cd77-39ab-4de3-a453-791a1c7b848f">|
=> refactor: format expiration date for the ignored details panel [IDE-489]

infrastructure/code/convert.go
=> fix: decode path component correctly

application/server/configuration_test.go, infrastructure/code/code.go, internal/vcs/git_utils.go, internal/vcs/git_utils_test.go
=> feat: allow base scan if uncommited changes [IDE-483]

domain/ide/codelens/codelens_test.go, infrastructure/oss/code_actions.go, infrastructure/oss/oss_test.go
=> fix: don't add code actions to empty range

README.md, application/server/configuration.go, application/server/configuration_test.go, domain/snyk/persistence/git_persistence_provider.go, domain/snyk/persistence/git_persistence_provider_test.go, infrastructure/code/code.go, internal/types/lsp.go, internal/vcs/git_utils.go
- Rename Configuration.FolderConfig to FolderConfigs since it's an array.
- Handle edge case when file doesn't exist on disk but in cache
=> Chore: rename folderconfig

application/server/server.go, application/server/server_test.go, domain/ide/codelens/codelens_test.go, domain/ide/command/folder_handler.go, domain/ide/hover/service_test.go, infrastructure/code/cache_test.go, infrastructure/code/code.go, infrastructure/code/code_test.go, infrastructure/code/fake_snyk_code_api_service.go, infrastructure/learn/service_test.go, infrastructure/oss/cli_scanner.go, infrastructure/oss/vulnerability_count.go, infrastructure/oss/vulnerability_count_test.go, internal/debounce/Debouncer.go
Reduces load on the DidChange handler by debouncing calls and executing debounced callbacks in a goroutine.
Also renames "Vulnerabilities" to "Issues" in most places.
=> feat: performance improvement, debounce document changes [IDA-51]

application/server/configuration.go, internal/git_config/git_config.go
- Ensure persistence for git config after changing it.
=> fix: persist git config to repo after change

infrastructure/code/convert.go
=> fix: don't add base dir twice to codeflow filepath

.github/pull_request_template.md, infrastructure/code/convert_test.go
Adds the dataflow/codeflow filepath to the conversion test
=> chore: add dataflow filepath to test criteria

.github/workflows/build.yaml, .github/workflows/instance-tests.yaml, .github/workflows/release.yaml, Makefile, application/codeaction/codeaction.go, application/server/server_smoke_test.go, domain/ide/codelens/codelens.go
- If a fix does not fix all issues, a suffix is added `(x unfixable)`
- correctly use `issue/issues` depending on singular/plural
- also fixes the instance tests, that were running too many smoke test and took too long
- updated github actions to latest supported to fix deprecation notices from github
=> feat: improve oss quickfix and lense titles

application/config/config.go
=> fix: cli logging

infrastructure/code/code_html_test.go, infrastructure/code/template/details.html
Together with https://github.com/snyk/snyk-intellij-plugin/pull/578, this PR fixes some styling rules accordantly to Snyk Design System to keep the look and feel of products and experiences consistent.
|Before|After|
|-|-|
|<img width="1488" alt="before-code" src="https://github.com/user-attachments/assets/1b3de0ca-8c6d-40d7-8748-2d6b0e7844e5">|<img width="1479" alt="after-code" src="https://github.com/user-attachments/assets/3476d7b4-49eb-4cfc-aefb-e8d8b4959b0a">|
=> fix: adjust Data Flow CSS rules

go.mod, go.sum
=> fix: panic in instrumentation when no origin url exists

.github/workflows/build.yaml, Makefile, application/config/config.go, domain/ide/command/code_fix_diffs_test.go, domain/ide/workspace/folder.go, go.mod, go.sum, infrastructure/analytics/analytics.go, infrastructure/authentication/auth_service_impl_test.go, infrastructure/cli/cli_fake.go, infrastructure/code/autofix.go, infrastructure/code/code.go, infrastructure/code/code_test.go, infrastructure/code/fake_snyk_code_api_service.go, internal/notification/notifier_mock.go, main.go
=> fix: race conditions

README.md
=> fix: readme sast enabled command

README.md, internal/types/lsp.go
=> feat: add `additionalParameters` to folderConfig struct [IDE-567]

application/server/server.go
=> fix: set ide name in case clientInfo is empty

application/server/server_smoke_test.go
=> fix: assertion in integration tests

domain/ide/codelens/codelens.go
=> fix: check if issue is new when returning code lenses

infrastructure/code/template/details.html, infrastructure/oss/template/details.html
=> fix: use es5 js for IE webview support

README.md, application/config/config.go, application/server/configuration.go, application/server/configuration_test.go, domain/ide/converter/converter.go, go.mod, go.sum, infrastructure/code/convert.go, infrastructure/code/convert_test.go, infrastructure/code/example_commit_fixes.go, infrastructure/iac/iac.go, internal/types/lsp.go, licenses/github.com/writeas/go-strip-markdown/LICENSE
=> feat: IDE-626_add-option-to-hide-hovers

infrastructure/code/template/details.html
=> fix: js error when no example commit fixes exist

.github/workflows/instance-tests.yaml, .github/workflows/release.yaml, application/config/config.go, application/di/init.go, application/di/test_init.go, application/server/configuration.go, application/server/configuration_test.go, application/server/server.go, application/server/server_smoke_test.go, domain/ide/command/command_service.go, domain/snyk/scanner/scanner.go, go.mod, go.sum, infrastructure/authentication/auth_configuration.go, infrastructure/authentication/auth_service_impl.go, infrastructure/cli/initializer.go, infrastructure/oss/cli_scanner.go, infrastructure/oss/inline_value.go, infrastructure/oss/oss_integration_test.go, infrastructure/oss/vulnerability_count.go, infrastructure/oss/vulnerability_count_test.go, infrastructure/snyk_api/snyk_api.go, internal/types/lsp.go, ls_extension/main.go
- adds on/offline handling to not logout on networking issues
- updates to go-application-framework that supports setting the log level on network logging
- don't initialize WF Engine if not in standalone mode
https://github.com/user-attachments/assets/64c23c40-80b1-47bb-aa33-c20efc420e6b
=> fix: oauth offline detection

Makefile
=> fix: increase timeout for tests

application/server/server.go
=> fix: increase timeout for health check, call website

infrastructure/code/code.go, infrastructure/code/code_html.go, infrastructure/code/code_html_test.go, infrastructure/code/code_test.go, infrastructure/code/template/details.html
Make issue data available for the clients rendering AI Fixes and update UI.
This change need https://github.com/snyk/snyk-intellij-plugin/pull/596
- IDE-579
- IDE-580
=> feat: AI Fix for IntelliJ ⚡️ [IDE-580]

application/server/server.go
=> fix: disable offline checks

application/config/config.go, domain/ide/converter/converter.go, domain/ide/workspace/ui/diagnostics_overview_test.go, domain/snyk/code_issue_data.go, domain/snyk/iac_issue_data.go, domain/snyk/issues.go, domain/snyk/oss_issue_data.go, internal/types/lsp.go
add filterable issue type, isNew and isIgnored to all scan issues for all scan types.
=> feat: add filterable issue type to scan issue

go.mod, go.sum
=> fix: race condition when writing settings file

go.mod, go.sum, infrastructure/code/code.go, infrastructure/iac/iac.go, infrastructure/iac/template/index.html, infrastructure/iac/template/styles.css, internal/progress/progress.go
=> feat: iac style updates

domain/ide/command/code_fix_feedback.go, domain/ide/command/code_fix_feedback_test.go, infrastructure/code/constants.go, infrastructure/code/fake_snyk_code_api_service.go, infrastructure/code/issue_enhancer.go, infrastructure/code/issue_enhancer_test.go, infrastructure/code/snyk_code_http_client.go, infrastructure/code/snyk_code_http_client_interface.go
Track the behavior of the users regarding the Fix AI.
The events to track:
- users click button “Apply fix“
- users click thumbs up or down
=> Feat/ai fix feedback command [IDE-634]

domain/snyk/persistence/file_operation.go, internal/git_config/git_config.go, internal/vcs/git_utils.go
* If loading git Config fails because of an empty subsection error, attempt to delete the subsection.
* Before persisting a subsection ensure that the values are not empty.
=> fix: delete git empty section if exists

application/server/notification.go
=> fix: dont cancel progress if window/workDoneProgress/create fails

infrastructure/code/snyk_code_http_client_test.go
=> chore: remove unnecessary logging

application/codeaction/codeaction_test.go, application/server/server_smoke_test.go, domain/ide/command/get_active_user_test.go, domain/ide/command/get_feature_flag_status_test.go, domain/ide/command/logout_test.go, domain/ide/command/report_analytics_test.go, domain/ide/command/sast_enabled_test.go, domain/ide/workspace/folder_test.go, infrastructure/oss/oss_integration_test.go
=> fix: smoke tests

README.md
=> docs: add sdk callback to README.md

infrastructure/code/code.go
Added support for non git folder scan with consistent ignores.
=> feat: non git folder scan with consistent ignores IDE-700

application/server/server.go, domain/ide/command/clear_cache.go, domain/ide/command/folder_handler.go
=> fix: execute scans async in didChangeWorkspaceFolders and purgeCache

.github/upload-to-s3.sh, .github/workflows/release.yaml
=> fix: release pipeline

infrastructure/authentication/auth_configuration.go, infrastructure/authentication/auth_provider.go, infrastructure/authentication/auth_service.go, infrastructure/authentication/auth_service_impl.go, infrastructure/authentication/cli_provider.go, infrastructure/authentication/oauth_provider.go, infrastructure/authentication/oauth_provider_test.go, infrastructure/authentication/provider_fake.go
=> fix: auth mutex locking for callbacks

.github/workflows/release.yaml
=> fix: create gh release only on wf dispatch

.github/workflows/release.yaml
=> fix: build compiled license only on wf dispatch

application/server/server.go, application/server/server_smoke_test.go, application/server/server_test.go
=> fix: add reportAnalytics command to initialize response

application/server/server.go, licenses/github.com/hashicorp/hcl/go.mod
=> fix: send correct analytics integration info for VS

infrastructure/code/template/styles.css
This PR adds the styling necessary for the "disable apply-fix button after applying fix" functionality.
=> fix: add style for disabled ai fix button [IDE-779]

infrastructure/code/code.go, infrastructure/code/code_test.go
Filter code issues based on quality/security preferences.
=> fix: filter code quality and security issues based on config

infrastructure/code/code_html_test.go, infrastructure/code/template/details.html, infrastructure/code/template/styles.css
This PR provides the logic to make data-flow available for AI Fixes too with the according new proposed design.
=> fix: code data-flow order [IDE-764]

go.mod, go.sum
=> chore: update GAF

infrastructure/code/code.go
=> fix: check ctx for cancellation in `UploadAndAnalyzeWithIgnores`

application/server/execute_command_test.go, infrastructure/authentication/auth_configuration.go, infrastructure/authentication/auth_service_impl.go
Fixed:
* Endless loop caused by sending hasAuthenticated if token didn't change.
* Logging out multiple times after changing authentication method.
=> fix: auth bugs

domain/ide/workspace/workspace.go, internal/sdk/sdk.go
=> fix: only add workspace folder if not already added

ast/ast.go, ast/maven/parser.go, ast/maven/parser_test.go, ast/maven/testdata/maven-goof/pom.xml, ast/maven/testdata/maven-goof/sub/pom.xml, domain/ide/command/code_fix.go, domain/ide/command/code_fix_test.go, infrastructure/oss/cli_scanner.go, infrastructure/oss/code_actions.go, infrastructure/oss/html_range_finder.go, infrastructure/oss/issue.go, infrastructure/oss/maven_range_finder.go, infrastructure/oss/maven_range_finder_test.go, infrastructure/oss/npm_range_finder.go, infrastructure/oss/npm_range_finder_test.go, infrastructure/oss/oss_test.go, infrastructure/oss/parser/parser.go, infrastructure/oss/range_finder.go, infrastructure/oss/range_finder_test.go, infrastructure/oss/testdata/maven-goof/pom.xml, infrastructure/oss/testdata/maven-goof/sub/pom.xml, infrastructure/oss/testdata/maven-goof/sub/subsub/pom.xml
- highlight issue in sub pom.xml where the dep is included (unlimited hierarchies supported)
- offer a quickaction / code lens to fix it in the parent pom
**Not:**
- fix/highlight BOMs where the dependency versions are defined (depency.type = bom in parent pom)
=> feat: support maven pom hierarchies for highlighting & fixes [IDE-846]

domain/ide/command/folder_handler.go, internal/summary/summary_html.go, internal/summary/summary_html_test.go, internal/summary/template/details.html, internal/summary/template/styles.css
Initial summary panel notification handling and html generation, this will have follow-up changes.
=> feat: send initial summary panel notification

domain/scanstates/template/details.html, domain/scanstates/template/styles.css
=> fix: add ideScript to Summary html

domain/scanstates/template/details.html, domain/snyk/product.go, domain/snyk/scanner/base_scan.go, domain/snyk/scanner/scanner.go, domain/snyk/scanner/test_product_scanner.go, infrastructure/code/cache_test.go, infrastructure/code/code.go, infrastructure/code/code_test.go, infrastructure/iac/iac.go, infrastructure/iac/iac_test.go, infrastructure/oss/cli_package_scan.go, infrastructure/oss/cli_scanner.go, infrastructure/oss/oss_integration_test.go, infrastructure/oss/oss_test.go, internal/storedconfig/stored_config.go
=> fix: use workdir folderConfig for ref Scan

infrastructure/utils/fingerprint.go, infrastructure/utils/fingerprint_test.go
=> fix: ignore first dataflow element for oss fingerprint

domain/ide/workspace/folder.go, infrastructure/utils/fingerprint.go, infrastructure/utils/fingerprint_test.go, internal/delta/fuzzy_matcher.go, internal/delta/issue_enricher.go
=> fix: use unique issue identity for delta matching [IDE-1017] [IDE-991]

infrastructure/oss/oss_html_test.go, infrastructure/oss/template/details.html
Fixed the incorrect link to the non-existent /test endpoint by removing it.
=> fix: remove non-working link. we don't have an alternative, yet

shared_ide_resources/ui/html/ScanSummaryInit.html
=> fix: update reference html for scan summary with correct font scaling

application/server/configuration.go, application/server/server.go, go.mod, go.sum
=> fix: avoid logging sensitive data on config updates

infrastructure/code/template/styles.css
=> fix: code text color

domain/ide/command/generate_issue_description.go, domain/ide/workspace/workspace.go, domain/snyk/scanner/scanner.go
=> fix: panic when issue id doesnt match

application/server/notification.go, application/server/server_test.go, domain/ide/workspace/folder.go, domain/ide/workspace/workspace.go, domain/scanstates/scan_state_aggregator.go, domain/scanstates/summary_emitter.go, domain/scanstates/summary_html.go
=> fix: summary in-progress state

domain/scanstates/template/details.html, domain/scanstates/template/styles.css, shared_ide_resources/ui/html/ScanSummaryInit.html
Also changed the wording in the summary panel.
- N/A
- N/A - Couldn't see a linter for HTML/CSS
- N/A
- N/A
=> fix: Unsquish spinner and update summary text [IDE-1101]

internal/mcp/llm_binding.go, internal/mcp/llm_binding_test.go, internal/mcp/scan_tool.go, internal/mcp/scan_tool_test.go, mcp_extension/main.go
add integration name and integration version to spawned cli environment
=> fix: add analytics to mcp wrapper

internal/mcp/llm_binding.go, internal/mcp/snyk_tools.json, mcp_extension/main.go
=> fix: disable mcp json output

go.mod, go.sum, internal/mcp/llm_binding.go, internal/mcp/snyk_tools.json, licenses/github.com/yosida95/uritemplate/v3/LICENSE
=> feat(mcp): update MCP tools and configuration

infrastructure/code/ai_fix_handler.go
=> fix: disable explain

application/server/execute_command_test.go, domain/ide/command/workspace_scan.go
enriches the context with the scan source if given in the workspace scan command's args
=> fix: add scan source to workspace scan command

go.mod, go.sum, licenses/github.com/hashicorp/hcl/go.mod
=> fix: update code-client-go

internal/mcp/llm_binding.go
=> fix: check request origin

.github/workflows/mcp-readme-sync.yml, mcp_extension/README.md
As part of deploying the experimental MCP Server for Snyk, this adds some documentation for how to use it.
=> chore: add readme for mcp experimental

domain/ide/command/ignores_request.go, infrastructure/analytics/analytics.go, infrastructure/authentication/auth_service_impl.go
Added analytics for create ignore request.
=> feat: send analytic for create ignore

application/server/configuration.go, domain/ide/command/ignores_request.go, infrastructure/analytics/analytics.go, infrastructure/authentication/auth_service_impl.go
Added analytics for delta config change.
Added a timestamp bug in authentication analytics, where timestamp is nil when it should have a value.
=> feat: add instrumentation on config [IDE-1070]

application/server/configuration.go, domain/ide/command/ignores_request.go, domain/ide/workspace/workspace.go, infrastructure/analytics/analytics.go
=> fix: oldValue delta should be string in analytics

go.mod
=> chore: update go to 1.23.8

internal/mcp/llm_binding.go, internal/mcp/llm_binding_test.go
=> fix: mcp host check [IDE-1119]

internal/mcp/llm_binding.go, internal/mcp/llm_binding_test.go
=> fix: use request.Host to retrieve host header

domain/ide/command/code_fix_apply_edit.go, domain/ide/command/code_fix_diffs.go, domain/ide/command/code_fix_diffs_test.go, domain/ide/command/code_fix_feedback.go, domain/ide/command/code_fix_feedback_test.go, domain/ide/command/command_factory.go, domain/ide/command/generate_issue_description.go, domain/ide/command/navigate_to_range.go, infrastructure/code/code_html.go, infrastructure/code/code_html_inline_ignores_test.go, infrastructure/code/code_html_test.go, infrastructure/code/code_test.go, infrastructure/code/template/details.html
=> fix: display inline ignores, if feature flag is set

.windsurfrules
This commit introduces project-specific rules for Windsurf.
=> chore: add agent rules

infrastructure/code/template/details.html
=> chore: update Explanation header

shared_ide_resources/ui/html/ScanSummaryInit.html
=> chore: updating wording of initializing in summary [IDE-1235]

mcp_extension/llm_binding.go, mcp_extension/logging/logger.go, mcp_extension/main.go, mcp_extension/options.go, mcp_extension/scan_tool.go, mcp_extension/scan_tool_test.go
Changes
* Added file logging.
* Logger still logs to console output.
* Send `notifications/message` when logging.
=> feat(mcp): enhance logger capabilities

.gitleaksignore
=> chore: update commit hash of gitleaksignore entries for pat tests

domain/snyk/scanner/base_scan.go, domain/snyk/scanner/scanner_test.go, internal/vcs/git_utils.go
The current error message in the logs was not very good, the additional logging would have helped, but the proper error message will really help.
- N/A
- N/A
=> fix: better error message if no delta reference [IDE-1105]

mcp_extension/main.go, mcp_extension/main_test.go, mcp_extension/scan_tool.go, mcp_extension/snyk_tools.json, mcp_extension/utils.go, mcp_extension/utils_test.go
=> fix(mcp): add command param for python sca

application/config/config.go, domain/scanstates/summary_html.go, domain/scanstates/template/details.html, infrastructure/code/autofix.go, infrastructure/code/code.go, infrastructure/code/template/details.html, infrastructure/code/template/scripts.js
=> refactor: rename deepcode ai fix to snyk agent fix [IDE-1172]

mcp_extension/llm_binding.go, mcp_extension/llm_binding_test.go
=> fix: analytics env vars

.github/create-cli-pr.sh
=> chore: Update create-cli-pr.sh

mcp_extension/scan_tool.go, mcp_extension/snyk_tools.json
=> chore: update snyk_trust description

go.mod, go.sum, infrastructure/authentication/auth_service_impl.go, infrastructure/authentication/authentication_functions.go, mcp_extension/scan_tool.go, mcp_extension/snyk_tools.json
=> fix: use whoami wf to check auth status

.github/create-cli-pr.sh
=> fix: replace git whatchanged with git log

.github/create-cli-pr.sh
=> chore: use --name-status instead of --stat

.github/workflows/update-compatibility-matrix.yaml
=> chore(ci): correct docs sync path [IDA-563]

mcp_extension/trust/trust.go
=> fix(MCP): pre-populate trusted folders from env var [AG-5]
